'use strict';
let assetGeneration=0;
async function showAsset(){if(!location.hash.startsWith('#asset='))return;const generation=++assetGeneration,q=new URLSearchParams(location.hash.slice(1)),id=q.get('asset'),project=q.get('project'),key=q.get('key'),tag=q.get('tag'),target=document.getElementById('publicPass'),esc=v=>String(v||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
if(!/^[a-f0-9]{40}$/.test(id||'')||project!=='passpilot-69f7c'||!/^[A-Za-z0-9_-]{20,100}$/.test(key||'')){target.innerHTML='<section class="card"><h1>Identitätsstatus nicht prüfbar</h1><p>Registrierung oder Projektangaben fehlen. Keine Sicherheitsbewertung möglich.</p></section>';return;}
target.innerHTML='<section class="card"><h1>Aktuellen Status prüfen …</h1></section>';
try{const response=await fetch('https://firestore.googleapis.com/v1/projects/'+project+'/databases/(default)/documents/assetPublic/'+id+'?key='+key,{cache:'no-store',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error();const doc=await response.json(),f=doc.fields,a=Object.fromEntries(Object.entries(f).map(([k,v])=>[k,v.stringValue??v.integerValue??v.timestampValue]));if(a.assetId!==id||!['none','lost','stolen'].includes(a.report)||!/^\d+$/.test(String(a.revision)))throw Error();let tagStatus='';if(tag){const hashed=/^[a-f0-9]{40}$/.test(tag)?Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('tag|'+tag))),v=>v.toString(16).padStart(2,'0')).join(''):'';tagStatus=hashed&&a.tagKey===hashed?'QR-Kennung aktuell diesem Exemplar zugeordnet.':'QR-Kennung deaktiviert oder nicht aktuell zugeordnet.';}
if(generation!==assetGeneration||!location.hash.startsWith('#asset='))return;target.innerHTML='<section class="card"><h1>'+esc([a.brand,a.model].filter(Boolean).join(' ')||'Registriertes Exemplar')+'</h1><p>Asset-ID: PP-'+esc(id.toUpperCase().match(/.{1,5}/g).join('-'))+'</p><p><strong>'+esc({none:'Keine aktuelle Verlustmeldung in PassPilot',lost:'Verlust vom Nutzer gemeldet',stolen:'Diebstahl vom Nutzer gemeldet'}[a.report])+'</strong></p>'+(tagStatus?'<p>'+esc(tagStatus)+'</p>':'')+'<p>Serverstand '+esc(a.revision)+' · '+esc((a.updatedAt||'').slice(0,10))+'</p><p>Registrierung und Meldungen sind Nutzerangaben, keine unabhängige Prüfung. Fehlende Meldungen beweisen nicht, dass ein Gegenstand rechtmäßig verkauft wird. QR- und NFC-Links sind kopierbar.</p><p>Vor dem Kauf Gegenstand, Herstellerkennung, Fotos und Belege vergleichen. Die registrierte Übertragung muss vom Empfänger und Absender bestätigt werden.</p><p>Besitzernamen, Kontaktdaten, Seriennummern und Belege werden hier nicht angezeigt.</p></section>';document.title='Identitätsstatus – PassPilot';}
catch{if(generation===assetGeneration)target.innerHTML='<section class="card"><h1>Status nicht prüfbar</h1><p>Keine erreichbare Registrierung. Verbindung prüfen. Es wird kein Sicherheitsstatus behauptet.</p></section>';}}
window.addEventListener('hashchange',()=>{assetGeneration++;showAsset();});showAsset();
