'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),http=require('http'),{execFileSync}=require('child_process'),{chromium}=require('playwright');const root=path.resolve(__dirname,'..');execFileSync(process.execPath,[path.join(root,'scripts/build-web.cjs')]);
(async()=>{const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;try{const f=path.join(root,'web-dist',pathname.endsWith('/')?pathname+'index.html':pathname);res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.json')?'application/json':f.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true});try{const page=await browser.newPage({viewport:{width:390,height:800}}),errors=[],calls=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{if(!localStorage.getItem('passpilot-state-v2'))localStorage.setItem('passpilot-state-v2',JSON.stringify({settings:{introSeen:true},products:[],calendarEvents:[]}));});await page.goto('http://127.0.0.1:'+server.address().port);await page.evaluate(()=>{state.products.push(normalizeProduct({id:'simple',name:'PRIVATE_NAME',serial:'PRIVATE_SERIAL',notes:'PRIVATE_NOTE'}));saveState();openProduct('simple');});assert.equal(await page.locator('.product-primary-actions button').count(),3);assert(!await page.locator('.product-more').evaluate(d=>d.open));await page.locator('.help-fab').click();assert.equal(await page.locator('#assistantMode').innerText(),'Lokale Hilfe');await page.locator('#helpSearch').fill('Wie kann ich eine Rechnung hinzufügen?');await page.keyboard.press('Enter');assert.match(await page.locator('#assistantMessages').innerText(),/Gesamtsumme|Gesamtbetrag/);assert(!await page.locator('#assistantMessages').innerText().then(v=>v.includes('PRIVATE_SERIAL')));await page.keyboard.press('Escape');assert(!await page.locator('#helpDialog').evaluate(d=>d.open));assert(await page.locator('.help-fab').isVisible());
await page.locator('.help-fab').click();await page.evaluate(async()=>{for(let i=0;i<20;i++)await PassPilotAssistant.send('Anleitung finden');});assert.equal(await page.locator('#assistantMessages .chat-message').count(),24);await page.locator('[data-action=help-close]').click();
const old=await page.locator('.help-fab').boundingBox();await page.mouse.move(old.x+25,old.y+25);await page.mouse.down();await page.mouse.move(60,300,{steps:8});await page.mouse.up();assert(!await page.locator('#helpDialog').evaluate(d=>d.open));const moved=await page.locator('.help-fab').boundingBox();assert(moved.x<old.x&&moved.y<old.y);await page.reload();assert((await page.locator('.help-fab').boundingBox()).x<100);
// Floating nonmodal panel keeps the main page usable; form overlay keeps unsaved edits.
await page.locator('.help-fab').click();await page.locator('.bottom-nav [data-nav=products]').click();assert(await page.getByRole('heading',{name:'Meine Produkte',exact:true}).count());await page.locator('[data-action=help-close]').click();await page.evaluate(()=>modal(productForm()));await page.locator('[data-action=capture-manual]').click();await page.locator('[name=name]').fill('UNSAVED');await page.locator('#modal [data-action=help-open]').click();await page.keyboard.press('Escape');assert.equal(await page.locator('[name=name]').inputValue(),'UNSAVED');await page.keyboard.press('Escape');
await page.locator('[data-action=settings]').click();assert.equal(await page.locator('.settings-quick .settings-row').count(),5);assert(!await page.locator('.settings-advanced').evaluate(d=>d.open));await page.keyboard.press('Escape');
// Opt-in online call sends just the user's question; no automatic inventory attachment.
await page.evaluate(()=>{PassPilotAssistantConfig.enabled=true;PassPilotFirebase.user=()=> 'owner';PassPilotFirebase.token=async()=> 'TEST_TOKEN';});await page.route('**/api/assistant',async route=>{calls.push(route.request().postDataJSON());await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({answer:'<img src=x onerror=alert(1)> als Text, kein Befehl.'})});});await page.locator('.help-fab').click();await page.locator('.assistant-options summary').click();await page.locator('#assistantOnline').check();await page.locator('#helpSearch').fill('Wie verkaufe ich?');await page.keyboard.press('Enter');await page.getByText('<img src=x onerror=alert(1)> als Text, kein Befehl.',{exact:true}).waitFor();assert.deepEqual(calls,[{question:'Wie verkaufe ich?'}]);assert.equal(await page.locator('#assistantMessages img').count(),0);assert(!await page.evaluate(()=>JSON.stringify({...localStorage}).includes('Wie verkaufe ich?')));
for(const [width,height]of [[320,640],[390,400],[768,800]]){await page.setViewportSize({width,height});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await page.locator('#helpSearch').isVisible());}assert.deepEqual(errors,[]);console.log('PASS: simple actions/settings, floating draggable chat, retained form edits, local answers, explicit question-only KI opt-in, escaped output, session-only chat and mobile/keyboard layout.');}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exit(1)});
