'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),{chromium}=require('playwright');
(async()=>{const b=await chromium.launch({headless:true,args:['--no-sandbox']}),p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
try{
 await p.addInitScript(()=>{window.authCalls=[];window.rejectMail=false;window.verifiedMail=false;window.PassPilotAndroid={googleSignIn(){},firebaseRequest(id,url,method,body,token){const data=body?JSON.parse(body):{};authCalls.push({url,method,data});let status=200,result={};if(url.includes('signUp')||url.includes('signInWithIdp'))result={localId:'auth_fixture_125',email:'fixture@example.com',idToken:'TEST_SESSION_ONLY',refreshToken:'TEST_REFRESH_ONLY',expiresIn:'3600'};else if(url.includes('sendOobCode')&&rejectMail){status=429;result={error:{message:'TOO_MANY_ATTEMPTS_TRY_LATER'}};}else if(url.includes('accounts:lookup'))result={users:[{localId:'auth_fixture_125',email:'fixture@example.com',emailVerified:verifiedMail}]};else if(url.includes('securetoken.'))result={user_id:'auth_fixture_125',id_token:'TEST_REFRESHED_ONLY',refresh_token:'TEST_REFRESH_ONLY',expires_in:'3600'};else if(url.includes('/billingConfig/public'))result={fields:{googleClientId:{stringValue:'123456-public_test-client.apps.googleusercontent.com'}}};setTimeout(()=>PassPilotPlus.receive(id,{ok:true,status,body:result}),10);}};});
 await p.goto('file://'+path.resolve('app/src/main/assets/app/index.html'));await p.evaluate(()=>{state.settings.introSeen=true;state.settings.accountLoginRequired=false;closeModal();PassPilotFirebase.connect();});await p.locator('[data-action=firebase-auth-tab][data-mode=signUp]').click();await p.locator('#authEmail').fill('fixture@example.com');await p.locator('#authPassword').fill('Test password only');await p.locator('#firebaseAuth .primary-btn').click();await p.locator('#authStatus').waitFor();assert.match(await p.locator('#authStatus').innerText(),/Bestätigungs-E-Mail angefordert/);
 const calls=await p.evaluate(()=>authCalls);const mail=calls.find(x=>x.url.includes('sendOobCode'));assert.equal(mail.data.continueUrl,'https://passpilot-app.web.app/');assert.equal(mail.data.requestType,'VERIFY_EMAIL');
 await p.evaluate(()=>rejectMail=true);await p.locator('[data-action=firebase-verify]').click();await p.waitForFunction(()=>document.getElementById('authStatus').textContent.includes('Zu viele'));assert(await p.locator('[data-action=firebase-verify]').isEnabled());
 await p.evaluate(()=>{rejectMail=false;verifiedMail=true;});await p.locator('[data-action=firebase-check-verified]').click();await p.waitForFunction(()=>PassPilotFirebase.account().verified);assert((await p.evaluate(()=>authCalls)).some(x=>x.url.includes('securetoken.')));
 await p.locator('[data-action=firebase-logout]').click();await p.evaluate(()=>{const original=PassPilotPlus.request;PassPilotPlus.request=async(action,...args)=>{if(action!=='googleSignIn')return original(action,...args);const client=args[0];if(client!=='123456-public_test-client.apps.googleusercontent.com')throw Error('Client mismatch');return{idToken:'TEST_GOOGLE_TOKEN'};};});await p.locator('[data-action=firebase-google]').click();await p.waitForFunction(()=>PassPilotFirebase.account()?.verified);assert((await p.evaluate(()=>authCalls)).some(x=>x.url.includes('signInWithIdp')));
 assert(!await p.evaluate(()=>JSON.stringify({...localStorage}).includes('TEST_SESSION_ONLY')));assert.deepEqual(errors,[]);console.log('PASS: signup verification feedback, continue URL, resend rate-limit recovery, verified token refresh, Android public OAuth client retrieval and Google credential exchange.');
}finally{await b.close();}
})().catch(e=>{console.error(e);process.exit(1)});
