'use strict';
const assert=require('node:assert/strict'),path=require('path'),fs=require('fs'),http=require('http'),{chromium}=require('playwright'),{reveal}=require('./ui-helpers.cjs');const root=path.resolve(__dirname,'..');
(async()=>{const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname;try{const f=path.join(root,'web-dist',name.endsWith('/')?name+'index.html':name);res.setHeader('Content-Type',({'.js':'application/javascript','.json':'application/json','.css':'text/css'})[path.extname(f)]||'text/html');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true});try{const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{if(!localStorage.getItem('passpilot-state-v2'))localStorage.setItem('passpilot-state-v2',JSON.stringify({settings:{introSeen:true},products:[],calendarEvents:[]}));});await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('nav [data-action=new-product]').click();
const image=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=160;c.height=100;c.getContext('2d').fillRect(0,0,160,100);return c.toDataURL('image/png').split(',')[1];});
const payload={name:'bad.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')};
await page.evaluate(()=>PassPilotCapture.show(document.getElementById('productForm'),2));await page.locator('[data-capture-file="photo"][data-camera="false"]').setInputFiles(payload);await page.waitForFunction(()=>!!document.getElementById('productForm')._capture.photoFile);await page.locator('[data-action=capture-remove-photo]').click();assert.equal(await page.evaluate(()=>document.getElementById('productForm')._capture.photoFile),null);assert.equal(await page.evaluate(()=>document.getElementById('productForm')._capture.photoOriginal),null);assert(await page.locator('#capturePhotoPreview').isHidden());
await page.locator('[data-capture-file="photo"][data-camera="false"]').setInputFiles({...payload,name:'keep.png'});await page.waitForFunction(()=>!!document.getElementById('productForm')._capture.photoFile);
await page.evaluate(()=>PassPilotCapture.show(document.getElementById('productForm'),3));await page.locator('[name=name]').fill('Foto und PDFs');await page.locator('[name=price]').fill('50');await page.locator('[name=findManualAfterSave]').uncheck();
assert.equal(await page.locator('#captureSummary img').count(),1);await page.locator('[data-capture-documents]').setInputFiles([{name:'keep.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nkeep')},{name:'remove.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nremove')}]);await page.waitForFunction(()=>document.getElementById('productForm')._capture.documents.length===2);await page.locator('#captureDocuments [data-action=capture-remove-document]').last().click();assert.match(await page.locator('#captureDocuments').innerText(),/keep.pdf/);assert.doesNotMatch(await page.locator('#captureDocuments').innerText(),/remove.pdf/);
// Code removal preserves the user's edits and discards extracted-only values.
await page.evaluate(()=>{const f=document.getElementById('productForm');f._capture.codeOriginal=new File(['x'],'label.png',{type:'image/png'});f.elements.model.value='READ';f.elements.model.dataset.captureOrigin='code';f.elements.model.dataset.scanAutofilled='true';f.elements.brand.value='User';f.elements.brand.dataset.captureOrigin='code';f.elements.brand.dataset.scanUserEdited='true';PassPilotCapture.click('capture-remove-code',f.querySelector('[data-action=capture-remove-code]'));});assert.equal(await page.locator('[name=model]').inputValue(),'');assert.equal(await page.locator('[name=brand]').inputValue(),'User');
await page.locator('#productForm .form-actions .primary-btn').click();await page.waitForFunction(()=>state.products.length===1);const product=await page.evaluate(()=>state.products[0]);assert(product.coverImage);assert.equal(product.documents.length,1);assert.equal(product.documents[0].name,'keep.pdf');assert.equal(product.documents[0].share,false);assert.match(await page.evaluate(async()=>{const p=state.products[0];return (await getFile(p.id,p.documents[0].id)).text();}),/keep/);
assert(await page.locator('.history-product-context img').isVisible());await page.locator('nav [data-nav=dashboard]').click();await page.locator('.bottom-nav [data-action=more-open]').click();await page.locator('#modal [data-nav=history]').click();assert(await page.locator('.action-row .product-thumb').isVisible());assert.match(await page.locator('.action-row').innerText(),/50,00/);await page.reload();assert.equal(await page.evaluate(()=>state.products[0].documents.length),1);assert.deepEqual(errors,[]);console.log('PASS: remove/replace photo, review preview, multiple PDFs with per-file removal, private persistent document storage, preserved manual edits, history photo and price.');}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exit(1)});
