const {reveal}=require('./ui-helpers.cjs');
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require('playwright'),{execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..');execFileSync(process.execPath,[path.join(root,'scripts/build-web.cjs')]);
(async()=>{
 const dist=path.join(root,'web-dist'),mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.wasm':'application/wasm','.png':'image/png'};
 const server=http.createServer((req,res)=>{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname);let file=path.join(dist,name);if(name.endsWith('/'))file=path.join(file,'index.html');if(!file.startsWith(dist+path.sep)){res.writeHead(403);res.end();return;}try{const bytes=fs.readFileSync(file);res.writeHead(200,{'Content-Security-Policy':JSON.parse(fs.readFileSync(path.join(root,'firebase/firebase.json'))).hosting.headers[0].headers.find(h=>h.key==='Content-Security-Policy').value,'Content-Type':mime[path.extname(file)]||'application/octet-stream'});res.end(bytes);}catch{res.writeHead(404);res.end();}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port+'/';
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 try{
  const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(base))external.push(r.url());});
  await page.addInitScript(()=>{window.BarcodeDetector=undefined;if(!localStorage.getItem('passpilot-state-v2'))localStorage.setItem('passpilot-state-v2',JSON.stringify({products:[],calendarEvents:[],settings:{introSeen:true}}));});
  await page.goto(base);await reveal(page.locator('nav [data-action="add-entry"]'));await page.locator('nav [data-action="add-entry"]').click();await page.locator('#modal [data-action=entry-category][data-kind=product]').click();
  assert.equal(await page.locator('#productForm').getAttribute('data-capture-step'),'0');
  for(const slot of ['code','receipt','photo']){assert.equal(await page.locator(`[data-capture-file="${slot}"][data-camera="true"]`).getAttribute('capture'),'environment');assert.equal(await page.locator(`[data-capture-file="${slot}"][data-camera="false"]`).getAttribute('capture'),null);}
  await reveal(page.locator('[name="scanOnline"]'));await page.locator('[name="scanOnline"]').uncheck();
  const code=await page.evaluate(()=>PassPilotQR.toDataUrl('4006381333931',600));
  await page.locator('[data-capture-file="code"][data-camera="false"]').setInputFiles({name:'code.png',mimeType:'image/png',buffer:Buffer.from(code.split(',')[1],'base64')});
  await page.waitForFunction(()=>document.querySelector('[name="barcode"]').value==='4006381333931',null,{timeout:30000});
  await reveal(page.locator('[data-action="capture-next"]'));await page.locator('[data-action="capture-next"]').click();assert.equal(await page.locator('#productForm').getAttribute('data-capture-step'),'1');
  const data=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=1400;c.height=850;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,c.width,c.height);x.fillStyle='black';x.font='52px Arial';['MediaMarkt','Kaufdatum: 04.10.2026','Gesamt 39,90 EUR','Rechnungsnummer: R12345'].forEach((line,i)=>x.fillText(line,70,100+i*145));return c.toDataURL('image/png');});
  const file={name:'rechnung.png',mimeType:'image/png',buffer:Buffer.from(data.split(',')[1],'base64')};
  await page.locator('[data-capture-file="receipt"][data-camera="false"]').setInputFiles(file);
  await page.waitForFunction(()=>document.querySelector('#captureReceiptStatus').textContent.startsWith('Vorschläge direkt darunter prüfen.'),null,{timeout:120000});
  assert.equal(await page.locator('#captureDate').inputValue(),'2026-10-04');assert.match(await page.locator('#captureRetailer').inputValue(),/MediaMarkt/i);assert.equal(Number(await page.locator('#capturePrice').inputValue()),39.9);
  assert.equal(await page.locator('[name="price"]').inputValue(),'');assert.equal(await page.evaluate(()=>state.products.length),0);
  await reveal(page.locator('#captureApplyPrice'));await page.locator('#captureApplyPrice').check();await reveal(page.locator('[data-action="capture-next"]'));await page.locator('[data-action="capture-next"]').click();
  assert.equal(await page.locator('#productForm').getAttribute('data-capture-step'),'2');
  await page.locator('[data-capture-file="photo"][data-camera="false"]').setInputFiles(file);await page.waitForFunction(()=>document.querySelector('#capturePhotoStatus').textContent==='Produktfoto ausgewählt.');
  await reveal(page.locator('[data-action="capture-next"]'));await page.locator('[data-action="capture-next"]').click();assert.equal(await page.locator('#productForm').getAttribute('data-capture-step'),'3');
  await reveal(page.locator('[name="name"]'));await page.locator('[name="name"]').fill('Neues Testprodukt');await reveal(page.locator('#productForm [data-action="quick-details"]'));await page.locator('#productForm [data-action="quick-details"]').click();
  assert.equal(Number(await page.locator('[name="price"]').inputValue()),39.9);await reveal(page.locator('#productForm .form-actions .primary-btn'));await page.locator('#productForm .form-actions .primary-btn').click();
  await page.waitForFunction(()=>state.products.length===1);const result=await page.evaluate(async()=>{const p=state.products[0];return{p,receipt:await getFile(p.id,p.documents[0].id)};});assert(result.p.coverImage);assert.equal(result.p.documents[0].category,'Rechnung');assert.equal(result.p.documents[0].share,false);assert.equal(result.p.invoiceNumber,'R12345');assert.equal(result.p.purchaseDate,'2026-10-04');
  assert.equal(external.length,0,'Private images or OCR assets contacted an external host');
  await reveal(page.locator('[data-action="scan-document"]'));await page.locator('[data-action="scan-document"]').click();await page.locator('#pdfPages').setInputFiles([file,{...file,name:'zweite-seite.png'}]);await page.waitForFunction(()=>document.getElementById('multiPdfForm').pages.length===2);await reveal(page.locator('#multiPdfForm .primary-btn'));await page.locator('#multiPdfForm .primary-btn').click();await page.waitForFunction(()=>state.products[0].documents.some(d=>d.type==='application/pdf'));
  const count=await page.evaluate(async()=>{const p=state.products[0],d=p.documents.find(d=>d.type==='application/pdf'),blob=await getFile(p.id,d.id),pdf=await PDFLib.PDFDocument.load(await blob.arrayBuffer());return pdf.getPageCount();});assert.equal(count,2);
  const pdfText=await page.evaluate(async()=>{const p=state.products[0],d=p.documents.find(d=>d.type==='application/pdf');return PassPilotWebTools.readText(await getFile(p.id,d.id));});assert.match(pdfText,/MediaMarkt/i);
  await page.evaluate(async()=>{const p=state.products[0],d=p.documents.find(d=>d.type==='application/pdf');await PassPilotPlus.openFile(p.id,d.id);});await page.getByText('1 / 2 · 100 %',{exact:true}).waitFor();await reveal(page.locator('[data-pdf-action="next"]'));await page.locator('[data-pdf-action="next"]').click();await page.getByText('2 / 2 · 100 %',{exact:true}).waitFor();await reveal(page.locator('[data-pdf-action="larger"]'));await page.locator('[data-pdf-action="larger"]').click();await page.getByText('2 / 2 · 125 %',{exact:true}).waitFor();await reveal(page.locator('#modal [data-action="close-modal"]').first());await page.locator('#modal [data-action="close-modal"]').first().click();
  const evidence=await page.evaluate(()=>{const p=state.products[0];p.history.push({type:'repair',details:'PRIVATE_REPAIR_COST',cost:99,public:false});return {hidden:saleSnapshot(p),shared:saleSnapshot(p,{includeEvidence:true})};});assert.equal(evidence.hidden.evidence,null);assert.equal(evidence.shared.evidence.repairs,1);assert.equal(evidence.shared.evidence.receipt,true);assert(!JSON.stringify(evidence.shared).includes('PRIVATE_REPAIR_COST'));

  await reveal(page.locator('nav [data-action="add-entry"]'));await page.locator('nav [data-action="add-entry"]').click();await page.locator('#modal [data-action=entry-category][data-kind=product]').click();await reveal(page.locator('[data-action="capture-next"]'));await page.locator('[data-action="capture-next"]').click();
  await page.evaluate(()=>{PassPilotWebTools.readText=()=>new Promise(resolve=>window.finishOldReceipt=resolve);});await page.locator('[data-capture-file="receipt"][data-camera="false"]').setInputFiles(file);await page.waitForFunction(()=>!!window.finishOldReceipt);
  await reveal(page.locator('[data-action="capture-cancel-reading"]'));await page.locator('[data-action="capture-cancel-reading"]').click();await reveal(page.locator('[data-action="capture-manual"]'));await page.locator('[data-action="capture-manual"]').click();await reveal(page.locator('#productForm [name="name"]'));await page.locator('#productForm [name="name"]').fill('Abgebrochene Erkennung');await reveal(page.locator('#productForm .form-actions .primary-btn'));await page.locator('#productForm .form-actions .primary-btn').click();await page.waitForFunction(()=>state.products.length===2);
  await page.evaluate(()=>finishOldReceipt('Kaufdatum: 01.01.2000\nGesamt 999,00 EUR\nMarke: PRIVATE_OLD'));await page.waitForTimeout(50);assert.equal(await page.evaluate(()=>state.products[1].purchaseDate),'');assert.equal(await page.evaluate(()=>state.products[1].price),'');
  await page.reload();assert.equal(await page.evaluate(()=>state.products.length),2);
  const handoff='a'.repeat(40);await page.goto(base+'pass/#handoff='+handoff);await page.getByRole('link',{name:'Produkt in PassPilot öffnen'}).click();await page.locator('#firebaseAuth').waitFor();assert.equal(await page.evaluate(()=>PassPilotPendingHandoff),handoff);await reveal(page.locator('#modal [data-action="close-modal"]').first());await page.locator('#modal [data-action="close-modal"]').first().click();
  assert.deepEqual(errors,[]);
  console.log('PASS: guided code→receipt→photo→review flow, genuine local browser OCR, ZXing gallery scan, camera/gallery separation, opt-in receipt price, private receipt persistence, two-page PDF generation, reload, zero external image/OCR requests.');
 }finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exit(1)});
