'use strict';
const assert=require('node:assert/strict'),{createDocumentHandler}=require('../assistant-backend/functions/document-handler.cjs');
(async()=>{let calls=0,quota=0,sent;const options={verifyToken:async token=>{if(token!=='owner'&&token!=='unverified')throw Error();return{uid:'owner',email_verified:token==='owner'};},quota:async()=>{quota++;return true;},providerKey:()=> 'SERVER_SECRET',fetchImpl:async(url,opts)=>{calls++;sent=JSON.parse(opts.body);assert.equal(opts.headers.Authorization,'Bearer SERVER_SECRET');return{ok:true,json:async()=>({output:[{content:[{type:'output_text',text:JSON.stringify({name:'Sony WH-1000XM5',brand:'Sony',model:'WH-1000XM5',price:'129.99',purchaseDate:'2026-10-04',buyerAddress:'PRIVATE_ADDRESS'})}]}]})};}};const handler=createDocumentHandler(options);async function call(body,headers={authorization:'Bearer owner',origin:'https://passpilot-app.web.app'},custom=handler){const res={code:200,headers:{},set(k,v){this.headers[k]=v;return this;},status(c){this.code=c;return this;},json(b){this.body=b;return this;},end(){return this;}};await custom({method:'POST',headers,body},res);return res;}
const image={kind:'receipt',image:'data:image/jpeg;base64,AAAA'};
assert.equal((await call(image,{})).code,401);assert.equal((await call(image,{authorization:'Bearer unverified'})).code,403);assert.equal((await call(image,{authorization:'Bearer owner',origin:'https://evil.example'})).code,403);
for(const body of [{...image,text:0},{...image,privateNote:'foo'},{kind:'receipt',image:'data:image/svg+xml;base64,AAAA'},{kind:'receipt',text:'x'},{kind:'receipt',text:'x'.repeat(24001)},{kind:'photo',text:'x'.repeat(50)}])assert.equal((await call(body)).code,400);
assert.equal(calls,0);assert.equal(quota,0);let result=await call(image);assert.equal(result.code,200);assert.equal(result.body.fields.brand,'Sony');assert(!JSON.stringify(result).includes('PRIVATE_ADDRESS'));assert(!JSON.stringify(result).includes('SERVER_SECRET'));assert.equal(sent.store,false);assert.equal(sent.text.format.schema.additionalProperties,false);assert.equal(sent.max_output_tokens,700);assert.equal(sent.input[0].content[1].type,'input_image');
result=await call({kind:'receipt',text:'Shop\nKaufdatum: 04.10.2026\nGesamt 129,99'});assert.equal(result.code,200);assert.equal(sent.input[0].content.length,1);assert(!JSON.stringify(sent).includes('image_url'));
assert.equal((await call(image,undefined,createDocumentHandler({...options,providerKey:()=>''}))).code,503);assert.equal((await call(image,undefined,createDocumentHandler({...options,quota:async()=>false}))).code,429);assert.equal(calls,2);
console.log('PASS: optional document KI verified authentication, origin allowlist, strict image/PDF-text payload, shared quota, server-only secret, untrusted-document instructions and whitelist response. No live provider call.');})().catch(e=>{console.error(e);process.exit(1)});
