const {reveal}=require('./ui-helpers.cjs');
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{execFileSync}=require('node:child_process'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..');execFileSync(process.execPath,[path.join(root,'scripts/build-web.cjs')]);const dist=path.join(root,'web-dist');
const mime={'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.gz':'application/gzip'};
(async()=>{const server=http.createServer((req,res)=>{let pathname=new URL(req.url,'http://localhost').pathname;if(pathname.endsWith('/'))pathname+='index.html';const p=path.join(dist,pathname);try{res.setHeader('Content-Type',mime[path.extname(p)]||'application/octet-stream');res.end(fs.readFileSync(p));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true});let records=new Map(),seq=0,commitRaces=0,requests=[],forceStaleChunk=false,staleChunkReads=0,raceWriter=null;
async function page(){const context=await browser.newContext({viewport:{width:360,height:800}});const p=await context.newPage();await p.addInitScript(()=>!localStorage.getItem('passpilot-state-v2')&&localStorage.setItem('passpilot-state-v2',JSON.stringify({version:4,settings:{introSeen:true},products:[],calendarEvents:[]})));await p.route('https://**googleapis.com/**',async route=>{const req=route.request(),url=req.url();let body=url.includes('securetoken.')?Object.fromEntries(new URLSearchParams(req.postData())):req.postDataJSON();requests.push({url,body});const response=(status,v)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(v)});if(url.includes('accounts:lookup'))return response(200,{users:[{localId:'owner_uid',email:'owner@example.com',emailVerified:true}]});if(url.includes('securetoken.'))return response(200,{user_id:'owner_uid',id_token:'TEST_ID_TOKEN',refresh_token:'TEST_REFRESH',expires_in:'3600'});if(url.includes('signInWithPassword'))return response(200,{localId:'owner_uid',idToken:'TEST_ID_TOKEN',refreshToken:'TEST_REFRESH',expiresIn:3600});const name=url.split('/v1/')[1]?.split('?')[0];if(name?.endsWith(':commit')){const write=body.writes[0],key=write.update?.name||write.delete,old=records.get(key);if(write.currentDocument.exists===false&&old||write.currentDocument.updateTime&&old?.updateTime!==write.currentDocument.updateTime){commitRaces++;return response(412,{error:{message:'CAS conflict'}});}if(write.delete)records.delete(key);else records.set(key,{...write.update,updateTime:'t'+(++seq)});return response(200,{writeResults:[{updateTime:records.get(key)?.updateTime}]});}if(req.method()==='GET'&&name?.endsWith('/chunks'))return response(200,{documents:[...records.values()].filter(d=>d.name.startsWith(name+'/'))});if(forceStaleChunk&&req.method()==='GET'&&name?.includes('/vaults/owner_uid/chunks/')){forceStaleChunk=false;staleChunkReads++;await raceWriter.evaluate(()=>{closeModal();state.products.push(normalizeProduct({id:'snapshotRace'+state.products.length,name:'New synchronized record'}));saveState();return PassPilotSync.run();});}if(req.method()==='GET')return records.has(name)?response(200,records.get(name)):response(404,{error:{message:'not found'}});if(req.method()==='PATCH'){const doc={name,fields:body.fields,updateTime:'t'+(++seq)};records.set(name,doc);return response(200,doc);}if(req.method()==='DELETE'){records.delete(name);return response(200,{});}throw Error('Unexpected request '+url);});await p.goto(origin);await p.evaluate(()=>PassPilotFirebase.auth('signInWithPassword','owner@example.com','NOT_SAVED_PASSWORD'));return p;}
try{const a=await page(),b=await page(),errors=[];a.on('pageerror',e=>errors.push(e.message));b.on('pageerror',e=>errors.push(e.message));
 await a.evaluate(async()=>{state.products.push(normalizeProduct({id:'p1',name:'PRIVATE PRODUCT',serial:'PRIVATE_SERIAL',notes:'PRIVATE_NOTE'}));const blob=new Blob(['PRIVATE_PDF_CONTENT'],{type:'application/pdf'});state.products[0].documents.push({id:'d1',name:'PRIVATE_RECEIPT.pdf',type:blob.type,size:blob.size,share:false});await putFile('p1','d1',blob);saveState();});
 await Promise.all([a.evaluate(()=>PassPilotSync.unlock('Separate sync password 123!',true)),b.evaluate(()=>PassPilotSync.unlock('Separate sync password 123!',true))]);await a.evaluate(()=>{closeModal();return PassPilotSync.run();});await b.evaluate(()=>{closeModal();return PassPilotSync.run();});
 assert.equal(await b.evaluate(()=>state.products[0].serial),'PRIVATE_SERIAL');assert.equal(await b.evaluate(async()=>await(await getFile('p1','d1')).text()),'PRIVATE_PDF_CONTENT');assert(!JSON.stringify([...records.values()]).includes('PRIVATE'));assert(!JSON.stringify(requests.filter(r=>r.url.includes('firestore'))).includes('PRIVATE'));
 assert(!await a.evaluate(()=>JSON.stringify({...localStorage}).includes('Separate sync password')));
 // Independent products added concurrently merge via compare-and-swap rather than overwrite.
 await Promise.all([a.evaluate(()=>{closeModal();state.products.push(normalizeProduct({id:'a2',name:'A NEW'}));saveState();return PassPilotSync.run();}),b.evaluate(()=>{closeModal();state.products.push(normalizeProduct({id:'b2',name:'B NEW'}));saveState();return PassPilotSync.run();})]);await a.evaluate(()=>{closeModal();return PassPilotSync.run();});await b.evaluate(()=>{closeModal();return PassPilotSync.run();});assert.deepEqual(await a.evaluate(()=>state.products.map(p=>p.id).sort()),['a2','b2','p1']);assert.deepEqual(await b.evaluate(()=>state.products.map(p=>p.id).sort()),['a2','b2','p1']);
 // Deletion propagates; old product is not silently resurrected.
 await a.evaluate(()=>{state.products=state.products.filter(p=>p.id!=='a2');saveState();return PassPilotSync.run();});await b.evaluate(()=>PassPilotSync.run());assert(!await b.evaluate(()=>state.products.some(p=>p.id==='a2')));
 // A writer can replace and clean up the manifest while another device reads old chunks.
 raceWriter=a;forceStaleChunk=true;await b.evaluate(()=>{closeModal();return PassPilotSync.run();});
 // Force a new revision so the reader cannot use its unchanged-manifest fast path.
 if(forceStaleChunk){await b.evaluate(()=>{state.settings.shareSerial=false;saveState();return PassPilotSync.run();});}
 assert.equal(staleChunkReads,1);assert(await b.evaluate(()=>state.products.some(p=>p.id.startsWith('snapshotRace'))));
 // The same race during unlocking retries safely, rather than reporting a bad password.
 await b.evaluate(()=>PassPilotSync.lock());forceStaleChunk=true;await b.evaluate(()=>PassPilotSync.unlock('Separate sync password 123!',true));assert.equal(staleChunkReads,2);
 // Simultaneous edits require explicit choice.
 await a.evaluate(()=>{state.products.find(p=>p.id==='p1').name='DEVICE A';saveState();return PassPilotSync.run();});await b.evaluate(()=>{state.products.find(p=>p.id==='p1').name='DEVICE B';saveState();window.conflictRun=PassPilotSync.run();});await b.locator('#syncConflicts').waitFor();assert.match(await b.locator('#syncConflicts').innerText(),/DEVICE A/);assert.match(await b.locator('#syncConflicts').innerText(),/DEVICE B/);await reveal(b.locator('#syncConflicts select'));await b.locator('#syncConflicts select').selectOption('local');await reveal(b.locator('#syncConflicts button[type=submit]'));await b.locator('#syncConflicts button[type=submit]').click();await b.evaluate(()=>window.conflictRun);await a.evaluate(()=>PassPilotSync.run());assert.equal(await a.evaluate(()=>state.products.find(p=>p.id==='p1').name),'DEVICE B');
 await b.evaluate(()=>PassPilotSync.lock());const before=await b.evaluate(()=>JSON.stringify(state));await assert.rejects(()=>b.evaluate(()=>PassPilotSync.unlock('Wrong sync password 123!',true)));assert.equal(await b.evaluate(()=>JSON.stringify(state)),before);
 // Loss has no history entry; theft persists after recovery and remains private.
 await a.evaluate(()=>{PassPilotSync.lock();const p=getProduct('p1');p.identity.individualSerial=true;p.identity.serialConfirmed=p.serial;closeModal();openProduct('p1');});const count=await a.evaluate(()=>getProduct('p1').history.length);await reveal(a.locator('[data-action=toggle-lost]').first());await a.locator('[data-action=toggle-lost]').first().click();await reveal(a.locator('[data-kind=lost]'));await a.locator('[data-kind=lost]').click();assert.equal(await a.evaluate(()=>getProduct('p1').history.length),count);await reveal(a.locator('[data-action=toggle-lost]').first());await a.locator('[data-action=toggle-lost]').first().click();await reveal(a.locator('[data-action=toggle-lost]').first());await a.locator('[data-action=toggle-lost]').first().click();await reveal(a.locator('[data-kind=stolen]'));await a.locator('[data-kind=stolen]').click();await reveal(a.locator('[data-action=toggle-lost]').first());await a.locator('[data-action=toggle-lost]').first().click();assert.equal(await a.evaluate(()=>getProduct('p1').history.filter(h=>h.type==='theft'&&!h.public).length),1);assert.equal(await a.evaluate(()=>getProduct('p1').status),'active');
 // Help overlays preserve an unfinished form and restore focus on Escape.
 await a.evaluate(()=>modal(productForm()));await reveal(a.locator('[data-action=capture-manual]'));await a.locator('[data-action=capture-manual]').click();await reveal(a.locator('#productForm [name=name]'));await a.locator('#productForm [name=name]').fill('UNSAVED');await reveal(a.locator('#modal [data-action=help-open]'));await a.locator('#modal [data-action=help-open]').click();await reveal(a.locator('#helpSearch'));await a.locator('#helpSearch').fill('Rechnung');await reveal(a.locator('[data-action=help-topic]').first());await a.locator('[data-action=help-topic]').first().click();await a.keyboard.press('Escape');assert.equal(await a.locator('#productForm [name=name]').inputValue(),'UNSAVED');
 // Every visible field gets an accessible label; keyboard focus stays in modal.
 const unlabeled=await a.locator('#modal input:not([type=hidden]),#modal select,#modal textarea').evaluateAll(nodes=>nodes.filter(n=>n.getClientRects().length&&!n.labels?.length&&!n.getAttribute('aria-label')).map(n=>n.name));assert.deepEqual(unlabeled,[]);await a.locator('#modal button').last().focus();await a.keyboard.press('Tab');assert(await a.evaluate(()=>document.getElementById('modal').contains(document.activeElement)));await a.keyboard.press('Escape');assert(!await a.locator('#modal').evaluate(d=>d.open));
 assert(await a.locator('meta[property="og:image"]').getAttribute('content'));assert(await a.locator('link[rel=canonical]').getAttribute('href'));await a.evaluate(()=>navigator.serviceWorker.ready.then(()=>{}));await a.waitForTimeout(300);await a.context().setOffline(true);await a.reload();assert(await a.locator('[data-action=new-product]').count());assert.equal(await a.evaluate(()=>state.products.find(p=>p.id==='p1').name),'DEVICE B');await a.context().setOffline(false);await a.evaluate(()=>PassPilotFirebase.auth('signInWithPassword','owner@example.com','NOT_SAVED_PASSWORD'));await a.evaluate(()=>PassPilotSync.unlock('Separate sync password 123!',true));await b.evaluate(()=>PassPilotSync.unlock('Separate sync password 123!',true));const prefix=[...records.keys()].find(k=>k.endsWith('/vaults/owner_uid'));const chunk=[...records.values()].find(d=>d.name.includes('/chunks/'));records.set(prefix+'/chunks/'+'f'.repeat(40)+'_0',{...chunk,name:prefix+'/chunks/'+'f'.repeat(40)+'_0'});a.once('dialog',d=>d.accept());await reveal(a.locator('[data-action=sync-delete]'));await a.locator('[data-action=sync-delete]').click();await a.getByText('Online-Sync-Bestand gelöscht.',{exact:true}).waitFor();assert(![...records.keys()].some(k=>k.startsWith(prefix)));await b.evaluate(()=>{closeModal();return PassPilotSync.run();});await b.evaluate(()=>PassPilotSync.open());assert.match(await b.locator('#syncStatus').innerText(),/gelöscht/);assert.deepEqual(errors,[]);console.log('PASS: encrypted two-device sync with files, concurrent first setup and salt reconciliation, snapshot replacement races, CAS/concurrent edits, deletion, conflicts, wrong password safety, theft retention, local help, focus/labels, metadata and offline reload. CAS retries: '+commitRaces);
}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exit(1)});
