'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),vm=require('node:vm'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
(async()=>{
 const license=fs.readFileSync('/workspace/private-artifacts/PassPilot-Dauerfreischaltcode.txt','utf8').trim(),service=require('../assistant-backend/functions/license-service.cjs');assert.equal(service.verify(license).grant,'lifetime');assert.throws(()=>service.verify(license+'x'));
 const docs=new Map(),db={doc:p=>({path:p}),runTransaction:fn=>fn({get:async ref=>({exists:docs.has(ref.path),data:()=>docs.get(ref.path)}),set:(ref,data)=>docs.set(ref.path,data)})};await service.redeem({db,uid:'firstAccountUid12345',code:license});await service.redeem({db,uid:'firstAccountUid12345',code:license});await assert.rejects(service.redeem({db,uid:'secondAccountUid12345',code:license}));
 let requested='';const w={PassPilotIdentity:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'app/src/main/assets/app/firebase.js'),'utf8'),{window:w,localStorage:{getItem:()=>null},fetch:async url=>{requested=url;return{ok:true,json:async()=>({fields:{}})}},AbortSignal,URLSearchParams});w.PassPilotWebConfig={projectId:'passpilot-69f7c',apiKey:'A'.repeat(35)};await w.PassPilotFirebase.get('modelFacts','a'.repeat(64),true);assert(requested.includes('modelFacts/'+'a'.repeat(64)));await assert.rejects(w.PassPilotFirebase.get('passes','a'.repeat(64),true));
 const server=http.createServer((req,res)=>{try{const p=new URL(req.url,'http://localhost').pathname,f=path.join(root,'web-dist',p.endsWith('/')?p+'index.html':p);res.setHeader('Content-Type',({'.js':'application/javascript','.mjs':'application/javascript','.wasm':'application/wasm','.json':'application/json','.css':'text/css'})[path.extname(f)]||'text/html');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:360,height:800}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port+'/');
 await page.evaluate(()=>{state.products=[normalizeProduct({id:'test',name:'LG Fernseher',brand:'LG',model:'42LC2R',serial:'PRIVATE_SERIAL',notes:'PRIVATE_NOTE'})];openProduct('test');});
 await page.evaluate(()=>{PassPilotFirebase.get=async()=>{throw Error('offline')};return PassPilotFacts.open('test')});assert.equal(await page.locator('[data-url*="geizhals.de"]').count(),1);assert.equal(await page.locator('[data-url*="idealo.de"]').count(),1);assert(!(await page.locator('#modal').innerHTML()).includes('PRIVATE_SERIAL'));
 await page.evaluate(()=>{closeModal();PassPilotUpgrades.open();});assert.equal(await page.locator('#subscriptionPlans h3').count(),3);assert.match(await page.locator('#subscriptionPlans').innerText(),/3,99/);assert.match(await page.locator('#subscriptionPlans').innerText(),/5,99/);await page.locator('#upgradeCode').fill(license);await page.locator('#upgradeCodeForm button').click();await page.waitForFunction(()=>document.getElementById('upgradeStatus').textContent.includes('Dauerfreischaltung aktiv'));assert.equal(await page.evaluate(()=>PassPilotUpgrades.lifetime()),true);
 const focus=await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=2000;c.height=1400;const x=c.getContext('2d');x.fillStyle='#161616';x.fillRect(0,0,c.width,c.height);x.translate(1000,700);x.rotate(25*Math.PI/180);x.fillStyle='#fff';x.fillRect(-450,-230,900,460);x.fillStyle='#000';x.font='55px Arial';['LG','MODEL: 42LC2R','S/N: TEST12345'].forEach((v,i)=>x.fillText(v,-390,-100+i*100));const b=await new Promise(r=>c.toBlob(r,'image/png'));window.testLabel=new File([b],'LG-label.png',{type:'image/png'});return PassPilotRecognition.labelFocus(testLabel);});assert(focus?.crop);assert(Math.abs(focus.angle+25)<7);
 const recognition=await page.evaluate(async()=>{const result=await PassPilotWebTools.readCodeImage(testLabel,()=>{});return PassPilotScan.parseLabel(result.text);});assert.equal(recognition.brand,'LG');assert.equal(recognition.model,'42LC2R');assert.equal(recognition.serial,'TEST12345');
 for(const width of [320,360,768]){await page.setViewportSize({width,height:800});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}assert.deepEqual(errors,[]);await browser.close();await new Promise(r=>server.close(r));console.log('PASS: comparison fallback/private-data exclusions, model ID access, three offers, signed lifetime license and one-account binding, real OCR of tilted LG label, responsive layout.');
})().catch(e=>{console.error(e);process.exit(1)});
