const {reveal}=require('./ui-helpers.cjs');
const assert=require('node:assert/strict'),path=require('node:path'),{chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:360,height:800}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.PassPilotAndroid={toolsStatus(id){setTimeout(()=>PassPilotPlus.receive(id,{ok:true,lock:false,reminders:false,backup:false}),0)},setReminderData(data){window.reminders=JSON.parse(data)},findManual(id,brand,model){window.manualQuery={brand,model};setTimeout(()=>PassPilotPlus.receive(id,{ok:true,results:[{url:'https://www.sony.com/manuals/WH-1000XM5.pdf',title:'Sony WH-1000XM5',source:'Herstellerquelle',type:'PDF',confidence:'Modell im Treffer enthalten – Inhalt prüfen'}]}),0)},openExternalLink(url){window.opened=url},printHtml(html){window.printed=html},readReceipt(id,data){setTimeout(()=>PassPilotPlus.receive(id,{ok:true,text:'MediaMarkt\n04.10.2026\nSumme 129,99 EUR\nArtikelnummer: ABC-123\nRechnungsnummer: R-777\nS/N: SERIAL77'}),0)}}});
 await page.goto('file://'+path.resolve(__dirname,'../app/src/main/assets/app/index.html'));
 await page.evaluate(()=>{state.settings.introSeen=true;saveState();closeModal()});
 await reveal(page.locator('nav [data-action="new-product"]'));await page.locator('nav [data-action="new-product"]').click();assert(await page.locator('#productForm.quick-product').count());assert.equal(await page.locator('#productForm [name="notes"]').isVisible(),false);
 await reveal(page.locator('[data-action="capture-manual"]'));await page.locator('[data-action="capture-manual"]').click();await reveal(page.locator('#productForm [name="name"]'));await page.locator('#productForm [name="name"]').fill('Schnelles Produkt');await reveal(page.locator('#productForm .form-actions .primary-btn'));await page.locator('#productForm .form-actions .primary-btn').click();await page.getByRole('heading',{name:'Schnelles Produkt',exact:true}).waitFor();
 await reveal(page.locator('[data-action="edit-product"]').first());await page.locator('[data-action="edit-product"]').first().click();await reveal(page.locator('#productForm [name="brand"]'));await page.locator('#productForm [name="brand"]').fill('Sony');await reveal(page.locator('#productForm [name="model"]'));await page.locator('#productForm [name="model"]').fill('WH-1000XM5');await reveal(page.locator('#productForm [name="serial"]'));await page.locator('#productForm [name="serial"]').fill('PRIVATE_SN');await reveal(page.locator('#productForm [name="location"]'));await page.locator('#productForm [name="location"]').fill('PRIVATE_ADDRESS');await reveal(page.locator('#productForm [name="retailer"]'));await page.locator('#productForm [name="retailer"]').fill('PRIVATE_RETAILER');await reveal(page.locator('#productForm [name="notes"]'));await page.locator('#productForm [name="notes"]').fill('PRIVATE_NOTE');await reveal(page.locator('#productForm [name="tags"]'));await page.locator('#productForm [name="tags"]').fill('#HomeOffice, Teuer, HomeOffice');await reveal(page.locator('#productForm [name="purchaseDate"]'));await page.locator('#productForm [name="purchaseDate"]').fill('2024-02-29');
 page.once('dialog',d=>d.accept('12'));await reveal(page.locator('[data-action="warranty-suggest"]'));await page.locator('[data-action="warranty-suggest"]').click();assert.equal(await page.locator('[name="warrantyUntil"]').inputValue(),'2025-02-28');await reveal(page.locator('#productForm .form-actions .primary-btn'));await page.locator('#productForm .form-actions .primary-btn').click();
 assert.deepEqual(await page.evaluate(()=>state.products[0].tags),['HomeOffice','Teuer']);
 await reveal(page.locator('[data-action="add-history"]').first());await page.locator('[data-action="add-history"]').first().click();await reveal(page.locator('#editHistoryForm [name="title"]'));await page.locator('#editHistoryForm [name="title"]').fill('Reparatur Tippfehler');await reveal(page.locator('#editHistoryForm [name="cost"]'));await page.locator('#editHistoryForm [name="cost"]').fill('59');await reveal(page.locator('#editHistoryForm .primary-btn'));await page.locator('#editHistoryForm .primary-btn').click();await page.locator('.timeline-item').filter({hasText:'Reparatur Tippfehler'}).locator('[data-action="edit-history"]').click();await reveal(page.locator('#editHistoryForm [name="title"]'));await page.locator('#editHistoryForm [name="title"]').fill('Reparatur korrigiert');await reveal(page.locator('#editHistoryForm [name="cost"]'));await page.locator('#editHistoryForm [name="cost"]').fill('69');await reveal(page.locator('#editHistoryForm .primary-btn'));await page.locator('#editHistoryForm .primary-btn').click();assert(await page.getByText('Reparatur korrigiert',{exact:false}).count());assert((await page.evaluate(()=>state.products[0].history)).some(h=>h.cost==='69'));
 page.once('dialog',d=>d.accept());await page.locator('.timeline-item').filter({hasText:'Reparatur korrigiert'}).locator('[data-action="delete-history"]').click();assert.equal(await page.evaluate(()=>state.products[0].history.length),1);assert.equal(await page.evaluate(()=>state.products[0].history[0].title),'Produkt angelegt');
 await reveal(page.locator('nav [data-nav="products"]'));await page.locator('nav [data-nav="products"]').click();await reveal(page.locator('#productSearch'));await page.locator('#productSearch').fill('PRIVATE_NOTE');assert.equal(await page.locator('#filteredProducts .product-row').count(),1);await reveal(page.locator('#productSearch'));await page.locator('#productSearch').fill('does-not-exist');assert.equal(await page.locator('#filteredProducts .product-row').count(),0);await reveal(page.locator('#productSearch'));await page.locator('#productSearch').fill('');await reveal(page.locator('.product-filters summary'));await page.locator('.product-filters summary').click();await reveal(page.locator('[data-filter="tag"]'));await page.locator('[data-filter="tag"]').selectOption('HomeOffice');assert.equal(await page.locator('#filteredProducts .product-row').count(),1);await reveal(page.locator('[data-action="reset-filters"]'));await page.locator('[data-action="reset-filters"]').click();await reveal(page.locator('#filteredProducts .product-row'));await page.locator('#filteredProducts .product-row').click();
 await reveal(page.locator('[data-action="find-manual"]'));await page.locator('[data-action="find-manual"]').click();await page.locator('[data-action="manual-result-save"]').waitFor();await reveal(page.locator('[data-action="manual-result-save"]'));await page.locator('[data-action="manual-result-save"]').click();assert.equal(await page.evaluate(()=>state.products[0].documents[0].share),false);assert.deepEqual(await page.evaluate(()=>manualQuery),{brand:'Sony',model:'WH-1000XM5'});
 await page.evaluate(()=>{window.exports=[];downloadJson=async x=>exports.push(structuredClone(x))});
 await reveal(page.locator('[data-action="transfer-product"]').first());await page.locator('[data-action="transfer-product"]').first().click();for(const key of ['location','serial','name','photo'])assert.equal(await page.locator('#safeTransferForm [name="'+key+'"]').isChecked(),false);await reveal(page.locator('#safeTransferForm button[type="submit"]'));await page.locator('#safeTransferForm button[type="submit"]').click();await page.waitForFunction(()=>exports.length===1);const transfer=await page.evaluate(()=>exports[0]);for(const key of ['location','serial','notes','name','retailer','price'])assert.equal(transfer.product[key],'',key);assert.equal(transfer.product.documents.length,0);assert.equal(await page.evaluate(()=>state.products[0].transfers.length),1);
 // Re-importing the same backup does not silently create copies; merge and copy are explicit.
 await page.evaluate(async()=>{window.backup={format:'passpilot-backup',state:structuredClone(state),files:[]};window.importDone=false;importPayload(backup).then(()=>importDone=true)});await page.locator('#importChoices').waitFor();await reveal(page.locator('#importChoices .primary-btn'));await page.locator('#importChoices .primary-btn').click();await page.waitForFunction(()=>importDone);assert.equal(await page.evaluate(()=>state.products.length),1);
 await page.evaluate(()=>{backup.state.products[0].name='BACKUP_NAME';window.importDone=false;importPayload(backup).then(()=>importDone=true)});await reveal(page.locator('#importChoices select'));await page.locator('#importChoices select').selectOption('replace');await reveal(page.locator('#importChoices .primary-btn'));await page.locator('#importChoices .primary-btn').click();await page.waitForFunction(()=>importDone);assert.equal(await page.evaluate(()=>state.products[0].name),'BACKUP_NAME');
 await page.evaluate(()=>{window.importDone=false;importPayload(backup).then(()=>importDone=true)});await reveal(page.locator('#importChoices select'));await page.locator('#importChoices select').selectOption('copy');await reveal(page.locator('#importChoices .primary-btn'));await page.locator('#importChoices .primary-btn').click();await page.waitForFunction(()=>importDone);assert.equal(await page.evaluate(()=>state.products.length),2);assert.notEqual(...await page.evaluate(()=>state.products.map(p=>p.id)));
 await page.evaluate(()=>openProduct(state.products[0].id));await reveal(page.locator('[data-action="receipt"]'));await page.locator('[data-action="receipt"]').click();await page.locator('#receiptPhoto').setInputFiles({name:'receipt.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jG1QAAAAASUVORK5CYII=','base64')});await page.waitForFunction(()=>document.querySelector('#receiptForm [name=price]').value==='129.99');assert.equal(await page.locator('#receiptForm [name="applyPrice"]').isChecked(),false);await reveal(page.locator('#receiptForm [name="applyIdentity"]'));await page.locator('#receiptForm [name="applyIdentity"]').check();page.once('dialog',d=>d.accept());await reveal(page.locator('#receiptForm .primary-btn'));await page.locator('#receiptForm .primary-btn').click();await page.waitForFunction(()=>state.products[0].documents.some(d=>d.category==='Rechnung'),null,{timeout:5000}).catch(async e=>{console.log(await page.evaluate(()=>({products:state.products,modal:document.getElementById('modal').innerHTML,toast:document.getElementById('toast').textContent})));console.log(errors);throw e;});assert.equal(await page.evaluate(()=>state.products[0].invoiceNumber),'R-777');assert.equal(await page.evaluate(()=>state.products[0].partNumber),'ABC-123');assert.equal(await page.evaluate(()=>state.products[0].price),'');
 const id=await page.evaluate(()=>state.products[0].id);await page.evaluate(id=>{const p=getProduct(id);p.qrCreatedAt='2026-10-04T12:00:00Z';p.publicSettings.serial=false;window.qr=publicSnapshot(p);},id);assert(!(await page.evaluate(()=>JSON.stringify(qr))).includes('PRIVATE'));assert((await page.evaluate(()=>PassPilotPublic.render(qr))).includes('Stand der Daten: 04.10.2026'));
 await page.evaluate(()=>PassPilotPlus.printDocument('Inventar','<p>Test</p>'));assert((await page.evaluate(()=>printed)).includes('Stand:'));
 await page.screenshot({path:'/workspace/toolchains/passpilot-1.11-details.png',fullPage:true});
 const cases=await page.evaluate(()=>({receipt:PassPilotPlus.receiptFields('Shop\n03.10.2026\n04.10.2026\nSUMME 12,00\nTOTAL 15,00'),csv:PassPilotPlus.csvCell('=HYPERLINK("x")'),ics:PassPilotPlus.calendarExport([{id:'a',title:'Titel, mit; Zeichen\nZweite Zeile',date:'2026-10-04',time:'',notes:'Privat'}])}));assert.equal(cases.receipt.purchaseDate,'');assert.equal(cases.receipt.price,'');assert(cases.csv.startsWith('"\''));assert(cases.ics.includes('DTEND;VALUE=DATE:20261005'));assert(cases.ics.includes('Titel\\, mit\\; Zeichen\\nZweite Zeile'));
 const chunked=await page.evaluate(async()=>{PassPilotAndroid.chunkTest=id=>{PassPilotPlus.receiveChunk(id,'{"ok":true,"text":"',false);PassPilotPlus.receiveChunk(id,'prüfen ✓"}',false);PassPilotPlus.receiveChunk(id,'',true)};return await PassPilotPlus.request('chunkTest')});assert.equal(chunked.text,'prüfen ✓');
 // Password encryption round-trip, tampering rejection and import cancellation are separately covered below.
 await reveal(page.locator('nav [data-nav="backup"]'));await page.locator('nav [data-nav="backup"]').click();await reveal(page.locator('[data-action="encrypted-backup"]'));await page.locator('[data-action="encrypted-backup"]').click();await reveal(page.locator('#passwordForm [name="password"]'));await page.locator('#passwordForm [name="password"]').fill('Testpassword123');await reveal(page.locator('#passwordForm .primary-btn'));await page.locator('#passwordForm .primary-btn').click();await page.waitForFunction(()=>exports.some(x=>x.format==='passpilot-encrypted'));await page.evaluate(()=>{window.encrypted=exports.find(x=>x.format==='passpilot-encrypted');window.importDone=false;importPayload(encrypted).then(()=>importDone=true)});await reveal(page.locator('#passwordForm [name="password"]'));await page.locator('#passwordForm [name="password"]').fill('Testpassword123');await reveal(page.locator('#passwordForm .primary-btn'));await page.locator('#passwordForm .primary-btn').click();await page.locator('#importChoices').waitFor();await reveal(page.locator('#importChoices .primary-btn'));await page.locator('#importChoices .primary-btn').click();await page.waitForFunction(()=>importDone);assert.equal(await page.evaluate(()=>state.products.length),2);
 for(const width of [320,360,768]){await page.setViewportSize({width,height:800});await page.evaluate(()=>openProduct(state.products[0].id));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: quick capture, edit/delete history, search/tags, leap-year warranty, explicit private transfer, duplicate skip/replace/copy, receipt review and saved image, manufacturer result persistence, timestamp QR privacy, CSV/ICS escaping, encrypted backup round-trip and responsive details.');
})().catch(e=>{console.error(e);process.exit(1)});
