const {reveal}=require('./ui-helpers.cjs');
const assert=require('node:assert/strict');
const path=require('node:path');
const {chromium}=require('playwright');
(async()=>{
  const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
  const context=await browser.newContext({viewport:{width:360,height:800}});
  await context.addInitScript(()=>{window.externalLinks=[];window.PassPilotAndroid={openExternalLink:url=>externalLinks.push(url)}});
  const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('file://'+path.resolve(__dirname,'../app/src/main/assets/app/index.html'));
  await page.evaluate(()=>localStorage.setItem('passpilot-state-v2',JSON.stringify({version:4,settings:{introSeen:true,ownerAlias:'PRIVATE_OWNER'},products:[{id:'test',name:'PRIVATE_NAME',brand:'Sony',model:'WH-1000XM5',barcode:'4548736132580',serial:'PRIVATE_SERIAL',notes:'PRIVATE_NOTES',location:'PRIVATE_ADDRESS',documents:[]}]})));
  await page.reload();await reveal(page.locator('.bottom-nav [data-nav="products"]'));await page.locator('.bottom-nav [data-nav="products"]').click();await reveal(page.locator('[data-action="open-product"]').first());await page.locator('[data-action="open-product"]').first().click();
  const manuals=page.locator('#productManuals');assert(await manuals.isVisible());
  await manuals.locator('[data-kind="model"]').click();await manuals.locator('[data-kind="barcode"]').click();
  const links=await page.evaluate(()=>externalLinks);
  assert.equal(new URL(links[0]).hostname,'www.google.com');assert(new URL(links[0]).searchParams.get('q').includes('WH-1000XM5'));assert(new URL(links[1]).searchParams.get('q').includes('4548736132580'));
  assert(!JSON.stringify(links).includes('PRIVATE'));
  assert.deepEqual(await page.evaluate(()=>['javascript:alert(1)','data:text/html,x','file:///test.pdf','http://example.com/test.pdf','https://user:pass@example.com/file.pdf','https://example.com\\evil','/relative.pdf'].map(PassPilotManuals.safeUrl)),Array(7).fill(''));
  await manuals.locator('[data-action="add-manual-link"]').click();
  await reveal(page.locator('#manualName'));await page.locator('#manualName').fill('PRIVATE_MANUAL_TITLE <img src=x onerror="window.leak=true">');
  const PDF='https://docs.example.com/manual.pdf#page=2';await reveal(page.locator('#manualUrl'));await page.locator('#manualUrl').fill(PDF);
  await reveal(page.locator('[data-action="preview-manual-link"]'));await page.locator('[data-action="preview-manual-link"]').click();assert.equal((await page.evaluate(()=>externalLinks)).at(-1),PDF);
  await reveal(page.locator('#manualLinkForm .primary-btn'));await page.locator('#manualLinkForm .primary-btn').click();
  const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('passpilot-state-v2')).products[0].documents[0]);
  assert.equal(stored.kind,'link');assert.equal(stored.url,PDF);assert.equal(stored.share,false);
  assert.equal(await manuals.locator('.document-row img').count(),0);assert.equal(await page.evaluate(()=>!!window.leak),false);
  await manuals.locator('[data-action="open-document"]').click();assert.equal((await page.evaluate(()=>externalLinks)).at(-1),PDF);
  await page.reload();await reveal(page.locator('.bottom-nav [data-nav="products"]'));await page.locator('.bottom-nav [data-nav="products"]').click();await reveal(page.locator('[data-action="open-product"]').first());await page.locator('[data-action="open-product"]').first().click();assert(await manuals.locator('.document-row').count());
  const QR=await page.evaluate(()=>JSON.stringify(publicSnapshot(state.products[0])));assert(!QR.includes('docs.example'));assert(!QR.includes('PRIVATE_MANUAL'));
  await page.evaluate(async()=>{window.exports=[];downloadJson=(payload,filename)=>exports.push(payload);await exportBackup();await exportTransfer('test')});
  const exported=await page.evaluate(()=>exports);assert.equal(exported[0].state.products[0].documents[0].url,PDF);assert.equal(exported[1].product.documents.length,0);
  await manuals.locator('[data-action="edit-manual-link"]').click();
  await reveal(page.locator('#manualName'));await page.locator('#manualName').fill('Hersteller-Anleitung');await reveal(page.locator('#manualUrl'));await page.locator('#manualUrl').fill('https://support.example.com/product/manuals');await reveal(page.locator('#manualLinkForm [name="share"]'));await page.locator('#manualLinkForm [name="share"]').check();await reveal(page.locator('#manualLinkForm .primary-btn'));await page.locator('#manualLinkForm .primary-btn').click();
  await page.evaluate(async()=>exportTransfer('test'));assert.equal((await page.evaluate(()=>exports)).at(-1).product.documents[0].url,'https://support.example.com/product/manuals');
  await manuals.locator('[data-action="add-manual-file"]').click();assert.equal(await page.locator('#documentForm [name="category"]').inputValue(),'Bedienungsanleitung');
  await page.locator('#documentForm [name="file"]').setInputFiles({name:'manual.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nTest manual\n%%EOF')});await reveal(page.locator('#documentForm .primary-btn'));await page.locator('#documentForm .primary-btn').click();
  await page.waitForFunction(()=>state.products[0].documents.length===2);assert.equal(await manuals.locator('.document-row').count(),2);
  assert(await page.evaluate(async()=>{const p=state.products[0],d=p.documents.find(d=>d.kind!=='link');return (await getFile(p.id,d.id))?.size>0}));
  page.once('dialog',d=>d.accept());await manuals.locator('[data-action="delete-document"]').first().click();assert.equal(await manuals.locator('.document-row').count(),1);
  await page.evaluate(()=>{const p=state.products[0];p.brand='';p.model='';p.barcode='';openProduct(p.id)});assert(await manuals.locator('[data-kind="model"]').isDisabled());assert(await manuals.locator('[data-kind="barcode"]').isDisabled());
  assert.equal(await page.evaluate(()=>PassPilotManuals.searchUrl({barcode:'4548736132580',serial:'04548736132580'},'barcode')),'');
  const normalized=await page.evaluate(()=>normalizeProduct({documents:[{kind:'link',url:'javascript:alert(1)'},{kind:'link',url:'https://docs.example.com/ok.pdf',id:'ok',share:false}]}).documents);assert.equal(normalized.length,1);
  for(const width of [320,360,768]){await page.setViewportSize({width,height:800});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))}
  assert.deepEqual(errors,[]);await browser.close();
  console.log('PASS: barcode/model PDF search without private data, guarded external links, add/open/edit/delete, reload persistence, private backup and optional transfer, QR exclusions, local manual PDF upload, missing identifiers, imported link validation and responsive UI.');
})().catch(e=>{console.error(e);process.exit(1)});
