const {reveal}=require('./ui-helpers.cjs');
const assert=require('node:assert/strict');
const path=require('node:path');
const {chromium}=require('playwright');
const jsQR=require('jsqr');
const http=require('node:http');
const fs=require('node:fs');
const viewerPath=path.resolve(__dirname,'../public-viewer');
const server=http.createServer((req,res)=>{const name=req.url.split('?')[0].slice(1)||'index.html';if(!['index.html','public-pass.js','styles.css','viewer.js','favicon.png'].includes(name)){res.writeHead(404);return res.end()}res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':name.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(path.join(viewerPath,name)))});
const appPath=path.resolve(__dirname,'../app/src/main/assets/app/index.html');
const PRIVATE=['PRIVATE_ALIAS','PRIVATE_NAME','PRIVATE_NOTES','PRIVATE_LOCATION','PRIVATE_RETAILER','PRIVATE_DOCUMENT','PRIVATE_PHOTO','PRIVATE_PURCHASE_PRICE','PRIVATE_HISTORY','PRIVATE_PUBLIC_NOTE','PRIVATE_PRODUCT_ID','PRIVATE_CALENDAR_TITLE','PRIVATE_CALENDAR_NOTES'];
const fixture={version:3,calendarEvents:[{id:'private-calendar-event',title:'PRIVATE_CALENDAR_TITLE',notes:'PRIVATE_CALENDAR_NOTES',date:'2026-10-22',productId:'PRIVATE_PRODUCT_ID'}],settings:{introSeen:true,ownerAlias:'PRIVATE_ALIAS',publicBaseUrl:''},products:[{id:'PRIVATE_PRODUCT_ID',category:'ebike',name:'PRIVATE_NAME',brand:'Cube',model:'Touring',serial:'OPTIONAL_SERIAL',purchaseDate:'2022-06-01',location:'PRIVATE_LOCATION',retailer:'PRIVATE_RETAILER',price:'PRIVATE_PURCHASE_PRICE',notes:'PRIVATE_NOTES',publicNote:'PRIVATE_PUBLIC_NOTE',coverImage:'PRIVATE_PHOTO',status:'active',publicSettings:{serial:true,purchaseDate:true},warrantyUntil:'2027-12-31',nextMaintenance:'2026-12-10',history:[{id:'private',title:'PRIVATE_HISTORY',details:'PRIVATE_NOTES',public:false},...Array.from({length:6},(_,i)=>({id:`public${i}`,date:'2026-10-01',title:`Service ${i}`,details:'Bremsen geprüft',public:true}))],documents:[{id:'doc',name:'PRIVATE_DOCUMENT',share:true}]}]};
const decode=url=>JSON.parse(Buffer.from(url.split('#pass=')[1],'base64url').toString());
const assertPrivateExcluded=data=>{const serialized=JSON.stringify(data);for(const value of PRIVATE)assert(!serialized.includes(value),`Leaked ${value}`);for(const key of ['notes','location','retailer','price','ownerAlias','documents','coverImage','id'])assert(!Object.hasOwn(data,key),`Unexpected ${key}`);};
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const viewerUrl='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:360,height:800}});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('file://'+appPath);
 await page.evaluate(data=>localStorage.setItem('passpilot-state-v2',JSON.stringify(data)),fixture);await page.reload();
 await reveal(page.locator('nav [data-nav="products"]'));await page.locator('nav [data-nav="products"]').click();
 await reveal(page.locator('[data-action="open-product"]').first());await page.locator('[data-action="open-product"]').first().click();
 await reveal(page.locator('[data-action="sale-product"]'));await page.locator('[data-action="sale-product"]').click();
 assert.equal(await page.locator('#saleTitle').inputValue(),'Cube Touring');
 assert.equal(await page.locator('input[name="includeSerial"]').isChecked(),false);
 assert.equal(await page.locator('input[name="includePurchaseDate"]').isChecked(),false);
 const preview=await page.locator('#salePreview').textContent();
 for(const value of [...PRIVATE,'OPTIONAL_SERIAL','2022-06-01'])assert(!preview.includes(value));
 await page.getByRole('button',{name:'Verkaufs-QR erstellen',exact:true}).click();
 await page.locator('#qrcode canvas').waitFor();
 let url=await page.locator('[data-action="copy-pass-url"]').getAttribute('data-url');
 let data=decode(url);assertPrivateExcluded(data);assert.equal(data.askingPrice,null);assert.equal(data.serial,'');assert.deepEqual(data.history,[]);
 assert.equal(data.purpose,'sale');assert.equal(new URL(url).protocol,'https:');
 const pixels=await page.locator('#qrcode canvas').evaluate(c=>{const p=c.getContext('2d').getImageData(0,0,c.width,c.height);return{data:Array.from(p.data),width:p.width,height:p.height}});
 const scanned=jsQR(new Uint8ClampedArray(pixels.data),pixels.width,pixels.height);
 assert(scanned,'QR image was not decodable');assert.equal(scanned.data,url);
 await page.getByRole('button',{name:'Verkaufsangaben bearbeiten',exact:true}).click();
 await reveal(page.locator('#askingPrice'));await page.locator('#askingPrice').fill('450');await reveal(page.locator('#saleCondition'));await page.locator('#saleCondition').selectOption('good');await reveal(page.locator('#saleDescription'));await page.locator('#saleDescription').fill('Ladegerät vorhanden.');
 for(const checkbox of await page.locator('input[name="saleHistory"]').all()) await checkbox.check();
 await page.getByRole('button',{name:'Verkaufs-QR erstellen',exact:true}).click();
 assert.equal(await page.locator('#saleForm').count(),1,'Too many history items were accepted');
 for(const checkbox of await page.locator('input[name="saleHistory"]').all()) await checkbox.uncheck();
 await reveal(page.locator('input[name="saleHistory"]').first());await page.locator('input[name="saleHistory"]').first().check();
 await reveal(page.locator('input[name="includeSerial"]'));await page.locator('input[name="includeSerial"]').check();await reveal(page.locator('input[name="includeWarranty"]'));await page.locator('input[name="includeWarranty"]').check();
 await page.getByRole('button',{name:'Verkaufs-QR erstellen',exact:true}).click();await page.locator('#qrcode canvas').waitFor();
 url=await page.locator('[data-action="copy-pass-url"]').getAttribute('data-url');data=decode(url);
 assertPrivateExcluded(data);assert.equal(data.askingPrice,450);assert.equal(data.serial,'OPTIONAL_SERIAL');assert.equal(data.warrantyUntil,'2027-12-31');assert.equal(data.purchaseDate,'');assert.equal(data.history.length,1);
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('passpilot-state-v2')));
 assert.equal(saved.products[0].price,'PRIVATE_PURCHASE_PRICE');assert.equal(saved.products[0].notes,'PRIVATE_NOTES');assert.equal(saved.products[0].sale.askingPrice,'450');
 await page.reload();await reveal(page.locator('nav [data-nav="products"]'));await page.locator('nav [data-nav="products"]').click();await reveal(page.locator('[data-action="open-product"]').first());await page.locator('[data-action="open-product"]').first().click();await reveal(page.locator('[data-action="sale-product"]'));await page.locator('[data-action="sale-product"]').click();assert.equal(await page.locator('#askingPrice').inputValue(),'450');
 await page.screenshot({path:'/workspace/toolchains/sale-form-1.3.png',fullPage:true});
 const buyer=await browser.newPage({viewport:{width:360,height:800}});const requests=[];buyer.on('request',r=>requests.push(r.url()));buyer.on('pageerror',e=>errors.push(e.message));
 await buyer.goto(viewerUrl+'/#pass='+url.split('#pass=')[1]);await buyer.getByRole('heading',{name:'Cube Touring',exact:true}).waitFor();
 const content=await buyer.locator('#publicPass').textContent();for(const value of PRIVATE)assert(!content.includes(value));assert(content.includes('450,00'));assert(content.includes('Service 0'));assert(!content.includes('Service 1'));
 assert(!requests.some(r=>r.includes('#pass=')||r.includes('OPTIONAL_SERIAL')),'Payload sent in network request');
 await buyer.screenshot({path:'/workspace/toolchains/buyer-pass-1.3.png',fullPage:true});
 const malicious={...data,title:'<img src=x onerror="window.PWNED=1">',description:'<script>window.PWNED=1</script>'};
 await buyer.goto(viewerUrl+'/#pass='+Buffer.from(JSON.stringify(malicious)).toString('base64url'));assert.equal(await buyer.locator('#publicPass img,#publicPass script').count(),0);assert.equal(await buyer.evaluate(()=>window.PWNED),undefined);
 for(const payload of ['!',Buffer.from('null').toString('base64url'),Buffer.from('[]').toString('base64url')]){await buyer.goto(viewerUrl+'/#pass='+payload);await buyer.getByRole('heading',{name:'Ungültiger Produktpass',exact:true}).waitFor();}
 assert.deepEqual(errors,[]);await browser.close();server.close();console.log('PASS: sale flow, QR scan, private field exclusions, explicit optional disclosures, persistence, buyer view, fragment privacy and hostile payloads.');
})().catch(e=>{console.error(e);process.exit(1)});
