'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),{chromium}=require('playwright'),api=require('../app/src/main/assets/app/obligations.js');
assert.equal(api.nextOccurrence({repeat:true,repeatEvery:1,repeatUnit:'months',repeatMode:'fixed',repeatAnchor:'2026-01-31',nextDate:'2026-02-28'},'2026-02-28'),'2026-03-31');
assert.equal(api.nextOccurrence({repeat:true,repeatEvery:1,repeatUnit:'months',repeatMode:'fixed',repeatAnchor:'2026-01-31'},'2026-04-02'),'2026-04-30');
assert.equal(api.nextOccurrence({repeat:true,repeatEvery:1,repeatUnit:'months',repeatMode:'completion',nextDate:'2026-02-28'},'2026-03-02'),'2026-04-02');
assert.equal(api.nextOccurrence({repeat:true,repeatEvery:2,repeatUnit:'weeks',repeatMode:'fixed',repeatAnchor:'2026-01-01'},'2026-01-20'),'2026-01-29');
(async()=>{const b=await chromium.launch({headless:true,args:['--no-sandbox']}),p=await b.newPage({viewport:{width:360,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
try{
 await p.goto('file://'+path.resolve('app/src/main/assets/app/index.html'));await p.evaluate(()=>{state.settings.introSeen=true;state.settings.accountLoginRequired=false;state.products=[normalizeProduct({id:'washer',name:'Waschmaschine',brand:'Bosch',model:'TEST-W123',returnUntil:localDate(new Date(Date.now()+5*86400000)),warrantyUntil:'2030-01-31',documents:[{id:'invoice',name:'Mein Kaufbeleg.pdf',category:'Rechnung'},{id:'manual',kind:'link',name:'Herstelleranleitung',category:'Bedienungsanleitung',url:'https://www.bosch-home.com/example/manual.pdf'}]}),normalizeProduct({id:'expired',name:'Altes Gerät',warrantyUntil:'2020-01-01'})];state.calendarEvents=[normalizeCalendarEvent({id:'visit',title:'Werkstatttermin',date:localDate(),productId:'washer'})];saveState();closeModal();currentView='dashboard';render();});
 await p.locator('.bottom-nav [data-action=add-entry]').click();assert.equal(await p.locator('.add-options button').count(),4);await p.locator('[data-action=entry-category][data-kind=insurance]').click();assert.equal(await p.locator('[name=kind]').inputValue(),'insurance');assert(!await p.locator('[name=amount]').isVisible());await p.locator('[name=productId]').selectOption('washer');await p.locator('[name=title]').fill('Geräteversicherung');await p.locator('[name=endDate]').fill('2030-01-31');await p.locator('#obligationForm .primary-btn').click();assert.equal(await p.evaluate(()=>getProduct('washer').obligations[0].kind),'insurance');assert.equal(await p.evaluate(()=>state.products.length),2);
 await p.evaluate(()=>{closeModal();currentView='dashboard';render();});assert.match(await p.locator('.next-card').innerText(),/Werkstatttermin/);assert.doesNotMatch(await p.locator('.next-card').innerText(),/Altes Gerät/);await p.locator('[data-action=next-task][data-event-id=visit]').click();await p.locator('[data-action=calendar-complete]').click();await p.reload();assert(await p.evaluate(()=>state.calendarEvents[0].completedAt));assert(!await p.evaluate(()=>PassPilotOrganizer.tasks().some(e=>e.id==='visit')));assert(await p.evaluate(()=>getCalendarEvents().some(e=>e.id==='visit'&&e.completedAt)));
 await p.locator('.bottom-nav [data-action=add-entry]').click();await p.locator('[data-action=entry-category][data-kind=product]').click();assert.equal(await p.locator('.capture-inline-review').count(),1);await p.locator('#review-name').fill('Sofort korrigiert');await p.locator('#review-brand').fill('LG');assert.equal(await p.locator('#productForm [name=name]').inputValue(),'Sofort korrigiert');await p.evaluate(()=>{const f=document.getElementById('productForm');f.elements.model.value='TEST123';f.elements.model.dataset.scanAutofilled='true';PassPilotScan.refresh(f);});assert.equal(await p.locator('#review-model').inputValue(),'TEST123');assert.match(await p.locator('[data-review-hint=model]').innerText(),/Vorschlag/);await p.locator('#review-model').fill('Korrigiertes Modell');await p.evaluate(()=>{const f=document.getElementById('productForm');PassPilotCapture.show(f,3);});assert.equal(await p.locator('#productForm [name=model]').inputValue(),'Korrigiertes Modell');await p.locator('#productForm .form-actions .primary-btn').click();assert(await p.evaluate(()=>state.products.some(x=>x.name==='Sofort korrigiert'&&x.model==='Korrigiertes Modell')));
 // Local source answers reference existing data; arbitrary HTML stays text and protected credentials stay locked.
 await p.evaluate(()=>openProduct('washer'));await p.locator('.help-fab').click();assert.equal(await p.locator('#assistantProduct').inputValue(),'washer');await p.evaluate(()=>PassPilotAssistant.send('Wie lange ist das in Garantie?'));assert.match(await p.locator('#assistantMessages').innerText(),/31\.1\.2030/);assert.match(await p.locator('#assistantMessages').innerText(),/Dein Produktarchiv/);await p.evaluate(()=>PassPilotAssistant.send('Welche Rechnung gehört dazu?'));assert.equal(await p.locator('#assistantMessages .chat-message:last-child [data-doc-id=invoice]').count(),1);
 await p.evaluate(()=>{PassPilotFacts.fetchFacts=async()=>({price:'199.00',currency:'EUR',sourceUrl:'https://example.com/model',checkedAt:'2026-10-01T00:00:00Z',specs:[{label:'Leistung',value:'900 W',sourceUrl:'https://example.com/spec'}]});});await p.evaluate(()=>PassPilotAssistant.send('Welche Leistung hat das Produkt?'));assert.match(await p.locator('#assistantMessages').innerText(),/900 W/);assert.equal(await p.locator('.chat-references [data-url="https://example.com/spec"]').count(),1);await p.locator('[data-action=help-close]').click();
 await p.evaluate(()=>{closeModal();currentView='dashboard';render();});assert.match(await p.locator('[data-sync-summary]').innerText(),/Lokal gespeichert/);assert.deepEqual(await p.evaluate(()=>PassPilotSync.changes({price:10,notes:'PRIVATE A'},{price:20,notes:'PRIVATE B'})),['Kaufpreis','Private Notizen']);assert(!await p.evaluate(()=>PassPilotSync.describe({name:'Test',notes:'SECRET',deviceAccess:{value:'PROTECTED'}}).includes('SECRET')));
 await p.context().setOffline(true);assert.equal(await p.evaluate(()=>PassPilotSync.info().code),'offline');await p.context().setOffline(false);
 // One-time appointments do not terminate insurance coverage when marked done.
 await p.evaluate(()=>{const o=getProduct('washer').obligations[0];o.nextDate=localDate();o.repeat=false;PassPilotObligations.open('washer',o.id);});await p.locator('[data-action=obligation-complete]').click();assert.equal(await p.evaluate(()=>getProduct('washer').obligations[0].active),true);
 for(const width of [320,360,412,768]){await p.setViewportSize({width,height:800});await p.evaluate(()=>{closeModal();currentView='dashboard';render();});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('.bottom-nav [data-action=add-entry]').click();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('[data-action=entry-category][data-kind=service]').click();await p.locator('[name=repeat]').check();assert(await p.locator('[name=repeatMode]').isVisible());assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 assert.deepEqual(errors,[]);console.log('PASS: four direct add entries, linked insurance, combined tasks with persistent completion, inline scan corrections, local source-backed assistant, verified specs, safe sync preview/offline status, insurance retention and mobile layouts.');
}finally{await b.close();}
})().catch(e=>{console.error(e);process.exit(1)});
