const fs=require('node:fs'),path=require('node:path');const {initializeTestEnvironment,assertSucceeds,assertFails}=require('@firebase/rules-unit-testing');const {doc,setDoc,getDoc,deleteDoc,collection,getDocs,Timestamp,serverTimestamp,updateDoc}=require('firebase/firestore');
(async()=>{
 const env=await initializeTestEnvironment({projectId:'demo-passpilot',firestore:{host:'127.0.0.1',port:8081,rules:fs.readFileSync(path.join(__dirname,'firestore.rules'),'utf8')}});
 const owner=env.authenticatedContext('owner',{email_verified:true}).firestore(),buyer=env.authenticatedContext('buyer',{email_verified:true,email:'BUYER@example.com'}).firestore(),stranger=env.authenticatedContext('stranger',{email_verified:true,email:'stranger@example.com'}).firestore(),unverified=env.authenticatedContext('unverified',{email_verified:false}).firestore(),anon=env.unauthenticatedContext().firestore();
 const expires=Timestamp.fromMillis(Date.now()+86400000),pass={ownerUid:'owner',active:true,expiresAt:expires,payload:JSON.stringify({v:1,title:'Public'}),updatedAt:serverTimestamp()};
 await assertSucceeds(setDoc(doc(owner,'passes/p1'),pass));await assertSucceeds(getDoc(doc(anon,'passes/p1')));await assertFails(setDoc(doc(stranger,'passes/p1'),{...pass,ownerUid:'stranger'}));await assertFails(setDoc(doc(unverified,'passes/p2'),{...pass,ownerUid:'unverified'}));await assertFails(getDocs(collection(anon,'passes')));
 await assertFails(updateDoc(doc(stranger,'passes/p1'),{active:false}));await assertSucceeds(updateDoc(doc(owner,'passes/p1'),{active:false}));await assertFails(getDoc(doc(anon,'passes/p1')));await assertSucceeds(getDoc(doc(owner,'passes/p1')));await assertSucceeds(updateDoc(doc(owner,'passes/p1'),{active:true}));
 await assertFails(setDoc(doc(stranger,'passes/p1/messages/m1'),{senderUid:'owner',text:'fake',createdAt:serverTimestamp()}));await assertSucceeds(setDoc(doc(stranger,'passes/p1/messages/m1'),{senderUid:'stranger',text:'Found it',createdAt:serverTimestamp()}));await assertSucceeds(getDoc(doc(owner,'passes/p1/messages/m1')));await assertFails(getDoc(doc(stranger,'passes/p1/messages/m1')));await assertFails(getDoc(doc(anon,'passes/p1/messages/m1')));
 const h={ownerUid:'owner',recipientUid:'',active:true,expiresAt:expires,payload:'{"format":"passpilot-transfer"}',updatedAt:serverTimestamp()};await assertSucceeds(setDoc(doc(owner,'handoffs/h1'),h));await assertFails(getDoc(doc(anon,'handoffs/h1')));await assertSucceeds(getDoc(doc(buyer,'handoffs/h1')));await assertFails(updateDoc(doc(buyer,'handoffs/h1'),{payload:'tampered',recipientUid:'buyer',active:false,updatedAt:serverTimestamp()}));await assertSucceeds(updateDoc(doc(buyer,'handoffs/h1'),{recipientUid:'buyer',active:false,updatedAt:serverTimestamp()}));await assertFails(updateDoc(doc(stranger,'handoffs/h1'),{recipientUid:'stranger',active:false,updatedAt:serverTimestamp()}));await assertFails(getDoc(doc(stranger,'handoffs/h1')));await assertSucceeds(getDoc(doc(owner,'handoffs/h1')));
 const restricted={...h,recipientEmail:'buyer@example.com'};await assertSucceeds(setDoc(doc(owner,'handoffs/restricted'),restricted));await assertSucceeds(getDoc(doc(buyer,'handoffs/restricted')));await assertFails(getDoc(doc(stranger,'handoffs/restricted')));await assertFails(updateDoc(doc(stranger,'handoffs/restricted'),{recipientUid:'stranger',active:false,updatedAt:serverTimestamp()}));await assertSucceeds(updateDoc(doc(buyer,'handoffs/restricted'),{recipientUid:'buyer',active:false,updatedAt:serverTimestamp()}));
 await assertSucceeds(setDoc(doc(owner,'passes/photos'),{...pass,payload:'x'.repeat(240000)}));await assertFails(setDoc(doc(owner,'passes/oversize'),{...pass,payload:'x'.repeat(250001)}));await assertSucceeds(setDoc(doc(owner,'handoffs/photos'),{...h,payload:'x'.repeat(240000)}));await assertFails(setDoc(doc(owner,'handoffs/oversize'),{...h,payload:'x'.repeat(250001)}));
 await assertSucceeds(setDoc(doc(owner,'households/f1'),{ownerUid:'owner',members:['buyer'],payload:'public product subset',updatedAt:serverTimestamp()}));await assertSucceeds(getDoc(doc(buyer,'households/f1')));await assertFails(getDoc(doc(stranger,'households/f1')));await assertFails(updateDoc(doc(buyer,'households/f1'),{members:['stranger']}));await assertSucceeds(updateDoc(doc(owner,'households/f1'),{members:[]}));await assertFails(getDoc(doc(buyer,'households/f1')));
 const snapshot='a'.repeat(40),vault={ownerUid:'owner',version:1,snapshot,count:1,bytes:20,salt:'A'.repeat(24),iv:'B'.repeat(16),updatedAt:serverTimestamp()};
 await assertSucceeds(setDoc(doc(owner,'vaults/owner'),vault));await assertSucceeds(getDoc(doc(owner,'vaults/owner')));await assertFails(getDoc(doc(anon,'vaults/owner')));await assertFails(getDoc(doc(stranger,'vaults/owner')));await assertFails(setDoc(doc(stranger,'vaults/owner'),{...vault,ownerUid:'stranger'}));await assertFails(setDoc(doc(unverified,'vaults/unverified'),{...vault,ownerUid:'unverified'}));await assertFails(updateDoc(doc(owner,'vaults/owner'),{plaintext:'private'}));
 const chunk={snapshot,index:0,data:'ENCRYPTED_BASE64',updatedAt:serverTimestamp()};await assertSucceeds(setDoc(doc(owner,'vaults/owner/chunks/'+snapshot+'_0'),chunk));await assertFails(getDoc(doc(stranger,'vaults/owner/chunks/'+snapshot+'_0')));await assertFails(updateDoc(doc(owner,'vaults/owner/chunks/'+snapshot+'_0'),{data:'rewrite'}));await assertFails(setDoc(doc(owner,'vaults/owner/chunks/'+snapshot+'_1'),{...chunk,index:0}));await assertFails(setDoc(doc(owner,'vaults/owner/chunks/'+snapshot+'_2'),{...chunk,index:2,data:'x'.repeat(180001)}));await assertSucceeds(deleteDoc(doc(owner,'vaults/owner/chunks/'+snapshot+'_0')));await assertSucceeds(deleteDoc(doc(owner,'vaults/owner')));
 await assertFails(setDoc(doc(owner,'unknown/doc'),{x:1}));await env.cleanup();console.log('PASS: verified owner writes, public active pass get only, revoke, private finder messages, handoff claim protection, family allowlist, private encrypted vault owner isolation, chunk validation and deny-by-default.');
})().catch(e=>{console.error(e);process.exit(1)});
