package com.passpilot.app;

import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.graphics.pdf.PdfDocument;
import android.net.Uri;
import android.os.*;
import android.provider.DocumentsContract;
import android.webkit.*;
import androidx.core.content.FileProvider;
import com.google.mlkit.vision.common.InputImage;
import com.google.mlkit.vision.text.TextRecognition;
import com.google.mlkit.vision.text.latin.TextRecognizerOptions;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;
import android.util.Base64;

final class AppTools {
 static final int SAVE=7201,TREE=7202,AUTH=7203,NOTIFY=7204;
 final MainActivity activity;final WebView web;final ExecutorService worker=Executors.newSingleThreadExecutor();final ExecutorService searches=Executors.newSingleThreadExecutor();
 final Map<String,PendingFile> files=new HashMap<>();String savingRequest,folderRequest,notifyRequest,authRequest;boolean authTarget,authenticating=false,unlocked=false;
 File savingFile;String savingName,savingMime;
 static class PendingFile {File file;FileOutputStream stream;String name,mime,mode;long size;PendingFile(File f,String n,String m,String mode)throws Exception{file=f;name=n;mime=m;this.mode=mode;stream=new FileOutputStream(f);}}
 AppTools(MainActivity a,WebView w){activity=a;web=w;}
 boolean local(){String url=web.getUrl();return !activity.isFinishing()&&!activity.isDestroyed()&&url!=null&&(url.equals("file:///android_asset/app/index.html")||url.startsWith("file:///android_asset/app/index.html#"));}
 void reply(String id,JSONObject data){activity.runOnUiThread(()->{if(!local())return;String encoded=data.toString();if(encoded.length()<=64000)web.evaluateJavascript("window.PassPilotPlus&&PassPilotPlus.receive("+JSONObject.quote(id)+","+encoded+");",null);else{for(int offset=0;offset<encoded.length();offset+=48000)web.evaluateJavascript("window.PassPilotPlus&&PassPilotPlus.receiveChunk("+JSONObject.quote(id)+","+JSONObject.quote(encoded.substring(offset,Math.min(offset+48000,encoded.length())))+",false);",null);web.evaluateJavascript("window.PassPilotPlus&&PassPilotPlus.receiveChunk("+JSONObject.quote(id)+",\"\",true);",null);}});}
 void ok(String id){reply(id,json("ok",true));}
 void error(String id,String message){reply(id,json("ok",false,"message",message));}
 String googleRequest;
 void googleSignIn(String id,String clientId){
  if(googleRequest!=null){error(id,"Eine Google-Anmeldung läuft bereits.");return;}
  if(clientId==null||!clientId.matches("^\\d+-[A-Za-z0-9_-]+\\.apps\\.googleusercontent\\.com$")){error(id,"Google-Anmeldung ist für Android noch nicht eingerichtet.");return;}
  if(prefs().getBoolean("lock",false)&&!unlocked){error(id,"Bitte zuerst PassPilot entsperren.");return;}
  googleRequest=id;
  try{
   com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption option=
    new com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption.Builder(clientId).build();
   androidx.credentials.GetCredentialRequest request=new androidx.credentials.GetCredentialRequest.Builder().addCredentialOption(option).build();
   androidx.credentials.CredentialManager.create(activity).getCredentialAsync(activity,request,null,
    androidx.core.content.ContextCompat.getMainExecutor(activity),new androidx.credentials.CredentialManagerCallback<androidx.credentials.GetCredentialResponse,androidx.credentials.exceptions.GetCredentialException>(){
     @Override public void onResult(androidx.credentials.GetCredentialResponse response){
      googleRequest=null;
      try{
       androidx.credentials.Credential credential=response.getCredential();
       if(!(credential instanceof androidx.credentials.CustomCredential)||
        !com.google.android.libraries.identity.googleid.GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL.equals(credential.getType()))throw new IllegalArgumentException();
       com.google.android.libraries.identity.googleid.GoogleIdTokenCredential token=
        com.google.android.libraries.identity.googleid.GoogleIdTokenCredential.createFrom(credential.getData());
       reply(id,json("ok",true,"idToken",token.getIdToken()));
      }catch(Exception e){error(id,"Google konnte die Anmeldung nicht bestätigen. Bitte erneut versuchen.");}
     }
     @Override public void onError(androidx.credentials.exceptions.GetCredentialException exception){
      googleRequest=null;
      error(id,exception instanceof androidx.credentials.exceptions.GetCredentialCancellationException?
       "Google-Anmeldung wurde abgebrochen.":"Google-Anmeldung nicht verfügbar. Prüfe Google-Anbieter, OAuth-Client-ID und Android-Signatur im Firebase-Projekt. Die E-Mail-Anmeldung funktioniert weiterhin.");
     }
    });
  }catch(Exception e){googleRequest=null;error(id,"Google-Anmeldung konnte nicht gestartet werden. Du kannst dich mit E-Mail anmelden.");}
 }
 void captureScreen(String id){
  if(prefs().getBoolean("lock",false)&&!unlocked){error(id,"Der gesperrte Bildschirm wird nicht aufgenommen.");return;}
  web.evaluateJavascript("Boolean(document.body.classList.contains('feedback-capture')&&window.PassPilotFeedback&&!PassPilotFeedback.protectedScreen())",allowed->{
   if(!"true".equals(allowed)||!local()){error(id,"Dieser Bereich wird ohne Aufnahme gemeldet.");return;}
   Bitmap bitmap=null;
   try{
    int width=web.getWidth(),height=web.getHeight();if(width<1||height<1)throw new IOException();
    float scale=Math.min(1f,Math.min(720f/width,1280f/height));
    bitmap=Bitmap.createBitmap(Math.max(1,Math.round(width*scale)),Math.max(1,Math.round(height*scale)),Bitmap.Config.ARGB_8888);
    Canvas canvas=new Canvas(bitmap);canvas.scale(scale,scale);web.draw(canvas);
    ByteArrayOutputStream bytes=new ByteArrayOutputStream();bitmap.compress(Bitmap.CompressFormat.JPEG,65,bytes);
    if(bytes.size()>300000){bytes.reset();bitmap.compress(Bitmap.CompressFormat.JPEG,40,bytes);}
    String image="data:image/jpeg;base64,"+Base64.encodeToString(bytes.toByteArray(),Base64.NO_WRAP);
    if(image.length()>420000)throw new IOException();
    reply(id,json("ok",true,"image",image));
   }catch(Exception e){error(id,"Aufnahme nicht verfügbar. Du kannst die Meldung ohne Bild senden.");}
   finally{if(bitmap!=null)bitmap.recycle();}
  });
 }
 android.content.SharedPreferences prefs(){return activity.getSharedPreferences("passpilot-tools",0);}
 void begin(String request,String fileId,String name,String mime,String mode){worker.execute(()->{try{if(!fileId.matches("[a-zA-Z0-9_-]{1,100}")||files.size()>3)throw new IOException();if(!Arrays.asList("export","view","pdf","backup").contains(mode))throw new IOException();File dir=new File(activity.getCacheDir(),"documents");dir.mkdirs();File file=File.createTempFile("passpilot_",".data",dir);files.put(fileId,new PendingFile(file,name.replaceAll("[\\\\/\\r\\n]","_").substring(0,Math.min(name.length(),120)),mime,mode));ok(request);}catch(Exception e){error(request,"Datei konnte nicht vorbereitet werden.");}});}
 void append(String id,String data){worker.execute(()->{PendingFile p=files.get(id);if(p==null)return;try{if(data.length()>100000||p.size>512L*1024*1024)throw new IOException();byte[] bytes=Base64.decode(data,Base64.NO_WRAP);p.stream.write(bytes);p.size+=bytes.length;}catch(Exception e){cancel(id);}});}
 void cancel(String id){PendingFile p=files.remove(id);if(p!=null){try{p.stream.close();}catch(Exception ignored){}p.file.delete();}}
 void finish(String request,String id){worker.execute(()->{PendingFile p=files.remove(id);if(p==null){error(request,"Dateiübertragung fehlgeschlagen.");return;}try{p.stream.close();if(p.mode.equals("backup")){validateBackup(p.file);File target=new File(activity.getFilesDir(),"latest-backup.json"),temp=new File(activity.getFilesDir(),"latest-backup.tmp");copy(p.file,new FileOutputStream(temp));if(!temp.renameTo(target))throw new IOException();p.file.delete();BackupReminderReceiver.writeBackup(activity);ok(request);return;}activity.runOnUiThread(()->{if(!local()){p.file.delete();return;}try{if(p.mode.equals("pdf")){openPdf(p.file);ok(request);}else if(p.mode.equals("view")){Uri uri=FileProvider.getUriForFile(activity,activity.getPackageName()+".fileprovider",p.file);activity.startActivity(new Intent(Intent.ACTION_VIEW).setDataAndType(uri,p.mime).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION));ok(request);}else{if(savingRequest!=null){p.file.delete();error(request,"Bitte den aktuellen Dateidialog zuerst schließen.");return;}savingRequest=request;savingFile=p.file;savingName=p.name;savingMime=p.mime;Intent intent=new Intent(Intent.ACTION_CREATE_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType(p.mime).putExtra(Intent.EXTRA_TITLE,p.name);activity.startActivityForResult(intent,SAVE);}}catch(Exception e){p.file.delete();error(request,"Datei konnte nicht geöffnet oder gespeichert werden.");}});}catch(Exception e){p.file.delete();error(request,"Datei konnte nicht gespeichert oder geprüft werden.");}});}
 static void validateBackup(File file)throws Exception{if(file.length()>512L*1024*1024)throw new IOException();JSONObject backup=new JSONObject(new String(read(file),StandardCharsets.UTF_8));if(!"passpilot-backup".equals(backup.optString("format"))||backup.optJSONObject("state")==null||backup.getJSONObject("state").optJSONArray("products")==null||backup.optJSONArray("files")==null)throw new IOException();}
 static void copy(File source,OutputStream output)throws IOException{try(InputStream in=new FileInputStream(source);OutputStream out=output){byte[] buffer=new byte[65536];int n;while((n=in.read(buffer))!=-1)out.write(buffer,0,n);}}
 void chooseFolder(String id){if(folderRequest!=null){error(id,"Bitte den aktuellen Ordnerdialog zuerst schließen.");return;}folderRequest=id;try{activity.startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION),TREE);}catch(Exception e){folderRequest=null;error(id,"Ordnerauswahl ist nicht verfügbar.");}}
 boolean result(int code,int result,Intent data){if(code==SAVE){String id=savingRequest;File file=savingFile;savingRequest=null;savingFile=null;if(id==null)return true;if(result!=Activity.RESULT_OK||data==null||data.getData()==null){if(file!=null)file.delete();error(id,"Speichern abgebrochen.");return true;}Uri target=data.getData();worker.execute(()->{try{copy(file,activity.getContentResolver().openOutputStream(target,"wt"));ok(id);}catch(Exception e){error(id,"Datei konnte nicht geschrieben werden.");}finally{file.delete();}});return true;}if(code==TREE){String id=folderRequest;folderRequest=null;if(result!=Activity.RESULT_OK||data==null){error(id,"Ordnerauswahl abgebrochen.");return true;}try{Uri tree=data.getData();activity.getContentResolver().takePersistableUriPermission(tree,Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);prefs().edit().putString("backupTree",tree.toString()).remove("lastSnapshot").putString("backupError","").apply();BackupReminderReceiver.schedule(activity);ok(id);}catch(Exception e){error(id,"Ordnerzugriff konnte nicht gespeichert werden.");}return true;}if(code==AUTH){authenticated(result==Activity.RESULT_OK);return true;}return false;}
 void readProductImage(String id,String data){worker.execute(()->{
  Bitmap bitmap=null;
  com.google.mlkit.vision.text.TextRecognizer recognizer=TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS);
  com.google.mlkit.vision.barcode.BarcodeScanner scanner=com.google.mlkit.vision.barcode.BarcodeScanning.getClient();
  try{
   if(!data.startsWith("data:image/")||data.length()>8000000)throw new IOException();
   byte[] bytes=Base64.decode(data.substring(data.indexOf(',')+1),Base64.DEFAULT);
   bitmap=BitmapFactory.decodeByteArray(bytes,0,bytes.length);if(bitmap==null)throw new IOException();
   InputImage image=InputImage.fromBitmap(bitmap,0);
   JSONArray codes=new JSONArray();
   for(com.google.mlkit.vision.barcode.common.Barcode barcode:com.google.android.gms.tasks.Tasks.await(scanner.process(image),20,TimeUnit.SECONDS)){
    if(barcode.getRawValue()!=null)codes.put(json("rawValue",barcode.getRawValue(),"format",barcode.getFormat()));
   }
   boolean productCode=false;for(int i=0;i<codes.length();i++){int format=codes.getJSONObject(i).optInt("format");if(format==com.google.mlkit.vision.barcode.common.Barcode.FORMAT_EAN_13||format==com.google.mlkit.vision.barcode.common.Barcode.FORMAT_EAN_8||format==com.google.mlkit.vision.barcode.common.Barcode.FORMAT_UPC_A||format==com.google.mlkit.vision.barcode.common.Barcode.FORMAT_UPC_E)productCode=true;}String text=readImageText(bitmap,recognizer,!productCode);
   reply(id,json("ok",true,"barcodes",codes,"text",text.substring(0,Math.min(text.length(),50000))));
  }catch(Exception e){error(id,"Produktbild konnte nicht gelesen werden. Näher aufnehmen oder manuell ergänzen.");}
  finally{if(bitmap!=null)bitmap.recycle();scanner.close();recognizer.close();}
 });}
 String readImageText(Bitmap bitmap,com.google.mlkit.vision.text.TextRecognizer recognizer,boolean retry)throws Exception{return readImageText(bitmap,recognizer,retry,System.nanoTime()+TimeUnit.SECONDS.toNanos(60));}
 String readImageText(Bitmap bitmap,com.google.mlkit.vision.text.TextRecognizer recognizer,boolean retry,long deadline)throws Exception{String best="";for(int rotation:new int[]{0,90,270,180}){long remaining=TimeUnit.NANOSECONDS.toMillis(deadline-System.nanoTime());if(remaining<500)break;String candidate=com.google.android.gms.tasks.Tasks.await(recognizer.process(InputImage.fromBitmap(bitmap,rotation)),Math.min(20000,remaining),TimeUnit.MILLISECONDS).getText();if(RecognitionQuality.score(candidate)>RecognitionQuality.score(best))best=candidate;if(!retry||RecognitionQuality.score(best)>=35)break;}return best.substring(0,Math.min(50000,best.length()));}
 void readReceipt(String id,String data){worker.execute(()->{Bitmap bitmap=null;com.google.mlkit.vision.text.TextRecognizer recognizer=null;try{if(data.startsWith("data:application/pdf;")){readPdfReceipt(id,data);return;}if(!data.startsWith("data:image/")||data.length()>10000000)throw new IOException();byte[] bytes=Base64.decode(data.substring(data.indexOf(',')+1),Base64.DEFAULT);bitmap=BitmapFactory.decodeByteArray(bytes,0,bytes.length);if(bitmap==null)throw new IOException();recognizer=TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS);reply(id,json("ok",true,"text",readImageText(bitmap,recognizer,true)));}catch(Exception e){error(id,"Beleg konnte nicht gelesen werden. Bitte näher und scharf fotografieren.");}finally{if(bitmap!=null)bitmap.recycle();if(recognizer!=null)recognizer.close();}});}
 void readPdfReceipt(String id,String data){File file=null;try{if(data.length()>28000000)throw new IOException();byte[] bytes=Base64.decode(data.substring(data.indexOf(',')+1),Base64.DEFAULT);file=File.createTempFile("receipt_",".pdf",activity.getCacheDir());try(FileOutputStream out=new FileOutputStream(file)){out.write(bytes);}try(ParcelFileDescriptor descriptor=ParcelFileDescriptor.open(file,ParcelFileDescriptor.MODE_READ_ONLY);android.graphics.pdf.PdfRenderer pdf=new android.graphics.pdf.PdfRenderer(descriptor)){com.google.mlkit.vision.text.TextRecognizer recognizer=TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS);StringBuilder result=new StringBuilder();int pagesRead=0;long deadline=System.nanoTime()+TimeUnit.SECONDS.toNanos(95);try{for(int i=0;i<Math.min(10,pdf.getPageCount())&&result.length()<50000&&System.nanoTime()<deadline;i++){try(android.graphics.pdf.PdfRenderer.Page page=pdf.openPage(i)){int width=2200,height=(int)(page.getHeight()*2200.0/page.getWidth());if(height>3000){width=(int)(width*3000.0/height);height=3000;}Bitmap image=Bitmap.createBitmap(width,height,Bitmap.Config.ARGB_8888);image.eraseColor(Color.WHITE);try{page.render(image,null,null,android.graphics.pdf.PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);String text=readImageText(image,recognizer,i==0,deadline);pagesRead++;result.append(text).append("\n");}finally{image.recycle();}}}}finally{recognizer.close();}reply(id,json("ok",true,"text",result.substring(0,Math.min(result.length(),50000)),"pagesRead",pagesRead));}}catch(Exception e){error(id,"Rechnungs-PDF konnte nicht gelesen werden (maximal zehn Seiten, keine Passwort-PDFs).");}finally{if(file!=null)file.delete();}}
 void createPdf(String id,String encoded){worker.execute(()->{try{JSONArray images=new JSONArray(encoded);if(images.length()<1||images.length()>20)throw new IOException();File file=File.createTempFile("scan_",".pdf",activity.getCacheDir());PdfDocument pdf=new PdfDocument();try{for(int i=0;i<images.length();i++){String data=images.getString(i);if(data.length()>6000000)throw new IOException();byte[] bytes=Base64.decode(data.substring(data.indexOf(',')+1),Base64.DEFAULT);Bitmap b=BitmapFactory.decodeByteArray(bytes,0,bytes.length);if(b==null)throw new IOException();PdfDocument.Page page=pdf.startPage(new PdfDocument.PageInfo.Builder(595,842,i+1).create());float scale=Math.min(575f/b.getWidth(),822f/b.getHeight());float w=b.getWidth()*scale,h=b.getHeight()*scale;page.getCanvas().drawColor(Color.WHITE);page.getCanvas().drawBitmap(b,null,new RectF((595-w)/2,(842-h)/2,(595+w)/2,(842+h)/2),new Paint(Paint.FILTER_BITMAP_FLAG));pdf.finishPage(page);b.recycle();}try(FileOutputStream out=new FileOutputStream(file)){pdf.writeTo(out);}}finally{pdf.close();}if(file.length()>20*1024*1024)throw new IOException();byte[] bytes=read(file);file.delete();reply(id,json("ok",true).put("data",Base64.encodeToString(bytes,Base64.NO_WRAP)));}catch(Exception e){error(id,"PDF konnte nicht erstellt werden. Weniger Seiten versuchen.");}});}
 void openPdf(File f){activity.startActivity(new Intent(activity,PdfViewerActivity.class).putExtra("path",f.getAbsolutePath()));}
 static URL safeUrl(String address)throws Exception{URI uri=new URI(address);String host=uri.getHost();if(!"https".equalsIgnoreCase(uri.getScheme())||host==null||uri.getUserInfo()!=null||uri.getPort()>0&&uri.getPort()!=443)throw new IOException();for(InetAddress resolved:InetAddress.getAllByName(host))if(resolved.isAnyLocalAddress()||resolved.isLoopbackAddress()||resolved.isLinkLocalAddress()||resolved.isSiteLocalAddress()||resolved.isMulticastAddress())throw new IOException();return uri.toURL();}
 static HttpURLConnection connection(String address,String method)throws Exception{String next=address;for(int i=0;i<4;i++){HttpURLConnection c=(HttpURLConnection)safeUrl(next).openConnection();c.setConnectTimeout(7000);c.setReadTimeout(7000);c.setInstanceFollowRedirects(false);c.setRequestMethod(method);c.setRequestProperty("User-Agent","PassPilot/1.11");int status=c.getResponseCode();if(status>=300&&status<400){String redirect=c.getHeaderField("Location");c.disconnect();if(redirect==null)throw new IOException();next=new URL(new URL(next),redirect).toString();continue;}return c;}throw new IOException();}
 void checkLink(String id,String url){worker.execute(()->{try{HttpURLConnection c=connection(url,"HEAD");int status=c.getResponseCode();c.disconnect();reply(id,json("ok",true).put("status",status>=200&&status<300?"ok":status==404||status==410?"gone":"unknown"));}catch(Exception e){reply(id,json("ok",true,"status","unknown"));}});}
 void downloadPdf(String id,String url){worker.execute(()->{File file=null;try{HttpURLConnection c=connection(url,"GET");if(c.getResponseCode()!=200)throw new IOException();File dir=new File(activity.getCacheDir(),"documents");dir.mkdirs();file=File.createTempFile("manual_",".pdf",dir);try(InputStream in=c.getInputStream();FileOutputStream out=new FileOutputStream(file)){byte[] buffer=new byte[65536];int n,total=0;while((n=in.read(buffer))!=-1){total+=n;if(total>20*1024*1024)throw new IOException();out.write(buffer,0,n);}}c.disconnect();byte[] bytes=read(file);file.delete();if(bytes.length<5||!new String(bytes,0,5,StandardCharsets.US_ASCII).equals("%PDF-"))throw new IOException();reply(id,json("ok",true).put("data",Base64.encodeToString(bytes,Base64.NO_WRAP)));}catch(Exception e){if(file!=null)file.delete();error(id,"Keine zugängliche PDF gefunden. Herstellerlink im Browser öffnen.");}});}
 void setLock(String id,boolean target){authRequest=id;authTarget=target;authenticate();}
 void resume(){if(prefs().getBoolean("lock",false)&&!unlocked&&!authenticating)authenticate();}
 void paused(){if(prefs().getBoolean("lock",false)&&!authenticating){unlocked=false;activity.setLocked(true);}}
 void authenticate(){KeyguardManager manager=(KeyguardManager)activity.getSystemService(Context.KEYGUARD_SERVICE);if(manager==null||!manager.isDeviceSecure()){if(authRequest!=null){error(authRequest,"Zuerst eine Geräte-PIN, ein Passwort oder Muster in Android einrichten.");authRequest=null;}return;}authenticating=true;activity.setLocked(true);if(Build.VERSION.SDK_INT>=30){android.hardware.biometrics.BiometricPrompt prompt=new android.hardware.biometrics.BiometricPrompt.Builder(activity).setTitle("PassPilot entsperren").setSubtitle("Mit Biometrie oder Geräte-PIN").setAllowedAuthenticators(android.hardware.biometrics.BiometricManager.Authenticators.BIOMETRIC_STRONG|android.hardware.biometrics.BiometricManager.Authenticators.DEVICE_CREDENTIAL).build();prompt.authenticate(new CancellationSignal(),activity.getMainExecutor(),new android.hardware.biometrics.BiometricPrompt.AuthenticationCallback(){@Override public void onAuthenticationSucceeded(android.hardware.biometrics.BiometricPrompt.AuthenticationResult result){authenticated(true);}@Override public void onAuthenticationError(int code,CharSequence message){authenticated(false);}});}else{Intent intent=manager.createConfirmDeviceCredentialIntent("PassPilot entsperren","Geräte-PIN / Passwort / Muster bestätigen");if(intent!=null)activity.startActivityForResult(intent,AUTH);else authenticated(false);}}
 void authenticated(boolean success){authenticating=false;unlocked=success;if(success){if(authRequest!=null){prefs().edit().putBoolean("lock",authTarget).apply();ok(authRequest);authRequest=null;}activity.setLocked(false);}else{if(authRequest!=null){error(authRequest,"Entsperren abgebrochen.");authRequest=null;if(!prefs().getBoolean("lock",false)){unlocked=true;activity.setLocked(false);}}}}
 void setReminders(String id,boolean enabled){if(enabled&&Build.VERSION.SDK_INT>=33&&activity.checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED){notifyRequest=id;activity.requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},NOTIFY);return;}if(enabled&&!((NotificationManager)activity.getSystemService(Context.NOTIFICATION_SERVICE)).areNotificationsEnabled()){error(id,"Benachrichtigungen in den Android-App-Einstellungen erlauben.");return;}prefs().edit().putBoolean("reminders",enabled).apply();BackupReminderReceiver.schedule(activity);ok(id);}
 void permission(int code,int[] results){if(code==NOTIFY&&notifyRequest!=null){String id=notifyRequest;notifyRequest=null;if(results.length>0&&results[0]==PackageManager.PERMISSION_GRANTED)setReminders(id,true);else error(id,"Benachrichtigungen wurden nicht erlaubt.");}}
 String nfcRequest;
 void writeNfc(String id,String address){try{URI nfcUrl=new URI(address);if(!"https".equalsIgnoreCase(nfcUrl.getScheme())||nfcUrl.getHost()==null||nfcUrl.getUserInfo()!=null)throw new IOException();if(address.length()>7000)throw new IOException();android.nfc.NfcAdapter adapter=android.nfc.NfcAdapter.getDefaultAdapter(activity);if(adapter==null||!adapter.isEnabled()){error(id,"NFC ist nicht verfügbar oder ausgeschaltet.");return;}if(nfcRequest!=null){error(id,"Ein NFC-Schreibvorgang läuft bereits.");return;}nfcRequest=id;android.widget.Toast.makeText(activity,"Leeren NFC-Tag an die Rückseite halten",android.widget.Toast.LENGTH_LONG).show();adapter.enableReaderMode(activity,tag->{try{android.nfc.tech.Ndef ndef=android.nfc.tech.Ndef.get(tag);android.nfc.NdefMessage message=new android.nfc.NdefMessage(android.nfc.NdefRecord.createUri(address));if(ndef==null)throw new IOException();ndef.connect();try{if(!ndef.isWritable()||ndef.getMaxSize()<message.toByteArray().length)throw new IOException();ndef.writeNdefMessage(message);}finally{ndef.close();}ok(id);}catch(Exception e){error(id,"Tag nicht beschreibbar oder zu klein. Für lange QR-Pässe ist ein größerer Tag nötig.");}finally{activity.runOnUiThread(()->{adapter.disableReaderMode(activity);nfcRequest=null;});}},android.nfc.NfcAdapter.FLAG_READER_NFC_A|android.nfc.NfcAdapter.FLAG_READER_NFC_B|android.nfc.NfcAdapter.FLAG_READER_NFC_F|android.nfc.NfcAdapter.FLAG_READER_NFC_V,null);web.postDelayed(()->{if(id.equals(nfcRequest)){adapter.disableReaderMode(activity);nfcRequest=null;error(id,"NFC-Schreiben beendet. Kein Tag erkannt.");}},60000);}catch(Exception e){error(id,"NFC-Schreiben konnte nicht gestartet werden.");}}
 void assistantRequest(String id,String question,String token){searches.execute(()->{try{
  if(question.trim().isEmpty()||question.length()>800||token.length()>10000)throw new IOException();
  URL url=new URL("https://europe-west3-passpilot-69f7c.cloudfunctions.net/passpilotAssistant");HttpURLConnection c=(HttpURLConnection)url.openConnection();c.setConnectTimeout(12000);c.setReadTimeout(25000);c.setInstanceFollowRedirects(false);c.setRequestMethod("POST");c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Authorization","Bearer "+token);c.setDoOutput(true);try(OutputStream out=c.getOutputStream()){out.write(new JSONObject().put("question",question.trim()).toString().getBytes(StandardCharsets.UTF_8));}int status=c.getResponseCode();InputStream source=status>=400?c.getErrorStream():c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream();if(source!=null)try(InputStream in=source){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1){if(out.size()+n>32768)throw new IOException();out.write(b,0,n);}}finally{c.disconnect();}JSONObject body=out.size()>0?new JSONObject(out.toString("UTF-8")):new JSONObject();reply(id,json("ok",true,"status",status,"body",body));
 }catch(Exception e){error(id,"KI nicht erreichbar. Nutze die lokale Hilfe.");}});}
 void documentRequest(String id,String payload,String token){searches.execute(()->{try{
  if(payload.length()>2600000||token.length()>10000)throw new IOException();
  URL url=new URL("https://europe-west3-passpilot-69f7c.cloudfunctions.net/passpilotDocument");HttpURLConnection c=(HttpURLConnection)url.openConnection();c.setConnectTimeout(12000);c.setReadTimeout(45000);c.setInstanceFollowRedirects(false);c.setRequestMethod("POST");c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Authorization","Bearer "+token);c.setDoOutput(true);try(OutputStream out=c.getOutputStream()){out.write(new JSONObject(payload).toString().getBytes(StandardCharsets.UTF_8));}int status=c.getResponseCode();InputStream source=status>=400?c.getErrorStream():c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream();if(source!=null)try(InputStream in=source){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1){if(out.size()+n>32768)throw new IOException();out.write(b,0,n);}}finally{c.disconnect();}JSONObject body=out.size()>0?new JSONObject(out.toString("UTF-8")):new JSONObject();reply(id,json("ok",true,"status",status,"body",body));
 }catch(Exception e){error(id,"KI nicht erreichbar. Nutze die lokale Hilfe.");}});}
 void checkAppUpdate(String id){worker.execute(()->{try{
  URL url=new URL("https://passpilot-app.web.app/download/latest.json");
  HttpURLConnection c=(HttpURLConnection)url.openConnection();c.setConnectTimeout(12000);c.setReadTimeout(12000);c.setInstanceFollowRedirects(false);c.setRequestProperty("Cache-Control","no-cache");
  if(c.getResponseCode()!=200)throw new IOException();ByteArrayOutputStream out=new ByteArrayOutputStream();try(InputStream in=c.getInputStream()){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1){if(out.size()+n>32768)throw new IOException();out.write(b,0,n);}}finally{c.disconnect();}
  JSONObject data=new JSONObject(out.toString("UTF-8"));String version=data.getString("version");int code=data.getInt("versionCode");if(!version.matches("[0-9]+\\.[0-9]+\\.[0-9]+-test")||code<1)throw new IOException();
  reply(id,json("ok",true,"version",version,"available",code>activity.getPackageManager().getPackageInfo(activity.getPackageName(),0).versionCode));
 }catch(Exception e){error(id,"Updateprüfung derzeit nicht möglich. Downloadseite öffnen oder später erneut versuchen.");}});}
 void firebaseRequest(String id,String address,String method,String body,String token){worker.execute(()->{try{URL url=new URL(address);if(!url.getProtocol().equals("https")||!Arrays.asList("identitytoolkit.googleapis.com","securetoken.googleapis.com","firestore.googleapis.com").contains(url.getHost())||url.getPort()!=-1||url.getUserInfo()!=null||body.length()>1000000||!Arrays.asList("GET","POST","PATCH","DELETE").contains(method))throw new IOException();HttpURLConnection c=(HttpURLConnection)url.openConnection();c.setConnectTimeout(12000);c.setReadTimeout(12000);c.setInstanceFollowRedirects(false);c.setRequestMethod(method);String sendBody=body;if(url.getHost().equals("identitytoolkit.googleapis.com"))c.setRequestProperty("X-Firebase-Locale","de");if(url.getHost().equals("securetoken.googleapis.com")&&!body.isEmpty()){JSONObject form=new JSONObject(body);sendBody="grant_type="+URLEncoder.encode(form.getString("grant_type"),"UTF-8")+"&refresh_token="+URLEncoder.encode(form.getString("refresh_token"),"UTF-8");c.setRequestProperty("Content-Type","application/x-www-form-urlencoded");}else c.setRequestProperty("Content-Type","application/json");if(!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);if(!body.isEmpty()){c.setDoOutput(true);try(OutputStream out=c.getOutputStream()){out.write(sendBody.getBytes(StandardCharsets.UTF_8));}}int status=c.getResponseCode();InputStream source=status>=400?c.getErrorStream():c.getInputStream();ByteArrayOutputStream result=new ByteArrayOutputStream();if(source!=null)try(InputStream in=source){byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))!=-1){if(result.size()+n>2000000)throw new IOException();result.write(buffer,0,n);}}c.disconnect();JSONObject response=result.size()>0?new JSONObject(result.toString("UTF-8")):new JSONObject();reply(id,json("ok",true,"status",status,"body",response));}catch(Exception e){error(id,"Firebase nicht erreichbar. Verbindung und Konfiguration prüfen.");}});}
 void status(String id){reply(id,json("ok",true,"lock",prefs().getBoolean("lock",false),"reminders",prefs().getBoolean("reminders",false),"backup",!prefs().getString("backupTree","").isEmpty(),"lastAutoBackup",prefs().getString("lastAutoBackup",""),"backupError",prefs().getString("backupError","")));}
 static JSONObject json(Object... values){JSONObject j=new JSONObject();try{for(int i=0;i<values.length;i+=2)j.put((String)values[i],values[i+1]);}catch(JSONException e){throw new IllegalArgumentException(e);}return j;}
 static byte[] read(File f)throws IOException{try(InputStream in=new FileInputStream(f);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[65536];int n;while((n=in.read(b))!=-1)out.write(b,0,n);return out.toByteArray();}}
 void close(){worker.execute(()->{for(String id:new ArrayList<>(files.keySet()))cancel(id);});worker.shutdown();searches.shutdownNow();}
}
