package com.passpilot.app;
import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.net.Uri;
import android.os.Build;
import android.provider.DocumentsContract;
import androidx.core.app.NotificationCompat;
import org.json.*;
import java.io.*;
import java.text.*;
import java.util.*;
public class BackupReminderReceiver extends BroadcastReceiver {
 static final String DAILY="com.passpilot.app.DAILY_CHECK";
 @Override public void onReceive(Context context,Intent intent){
  if(intent==null)return;
  String action=intent.getAction();
  // Accept only boot, our private alarm, or a previously scheduled pre-1.24 alarm.
  boolean legacy=action==null&&intent.getComponent()!=null&&BackupReminderReceiver.class.getName().equals(intent.getComponent().getClassName());
  if(!Intent.ACTION_BOOT_COMPLETED.equals(action)&&!DAILY.equals(action)&&!legacy)return;
  PendingResult pending=goAsync();new Thread(()->{try{checkReminders(context);writeBackup(context);}finally{schedule(context);pending.finish();}},"passpilot-daily").start();}
 static void schedule(Context context){AlarmManager alarms=(AlarmManager)context.getSystemService(Context.ALARM_SERVICE);PendingIntent alarm=PendingIntent.getBroadcast(context,0,new Intent(context,BackupReminderReceiver.class).setAction(DAILY),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);SharedPreferences prefs=context.getSharedPreferences("passpilot-tools",0);if(!prefs.getBoolean("reminders",false)&&prefs.getString("backupTree","").isEmpty()){alarms.cancel(alarm);return;}Calendar next=Calendar.getInstance();next.set(Calendar.HOUR_OF_DAY,9);next.set(Calendar.MINUTE,0);next.set(Calendar.SECOND,0);if(next.getTimeInMillis()<=System.currentTimeMillis())next.add(Calendar.DATE,1);alarms.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,next.getTimeInMillis(),alarm);}
 static void checkReminders(Context c){SharedPreferences prefs=c.getSharedPreferences("passpilot-tools",0);if(!prefs.getBoolean("reminders",false))return;try{SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd",Locale.ROOT);format.setLenient(false);Calendar today=Calendar.getInstance();today.set(Calendar.HOUR_OF_DAY,12);today.set(Calendar.MINUTE,0);today.set(Calendar.SECOND,0);String key=format.format(today.getTime());JSONArray reminders=new JSONArray(prefs.getString("reminderData","[]"));int count=0;for(int i=0;i<reminders.length();i++){JSONObject r=reminders.getJSONObject(i);if(r.has("accessUntil")&&r.optLong("accessUntil",0)<=System.currentTimeMillis())continue;Calendar date=Calendar.getInstance();date.setTime(format.parse(r.getString("date")));date.set(Calendar.HOUR_OF_DAY,12);date.set(Calendar.MINUTE,0);date.set(Calendar.SECOND,0);long days=Math.round((date.getTimeInMillis()-today.getTimeInMillis())/86400000.0);if(days==r.optInt("offset",7))count++;}if(count==0||key.equals(prefs.getString("lastNotification","")))return;NotificationManager manager=(NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE);if(Build.VERSION.SDK_INT>=26)manager.createNotificationChannel(new NotificationChannel("passpilot-deadlines","PassPilot Fristen",NotificationManager.IMPORTANCE_DEFAULT));PendingIntent open=PendingIntent.getActivity(c,1,new Intent(c,MainActivity.class),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);manager.notify(110,new NotificationCompat.Builder(c,"passpilot-deadlines").setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle("PassPilot: Fristen prüfen").setContentText(count+" Termine oder Fristen stehen an. App für Details öffnen.").setVisibility(NotificationCompat.VISIBILITY_PRIVATE).setContentIntent(open).setAutoCancel(true).build());prefs.edit().putString("lastNotification",key).apply();}catch(Exception ignored){}}
 static void writeBackup(Context c){SharedPreferences prefs=c.getSharedPreferences("passpilot-tools",0);String tree=prefs.getString("backupTree","");File latest=new File(c.getFilesDir(),"latest-backup.json");if(tree.isEmpty()||!latest.exists()||prefs.getLong("lastSnapshot",0)==latest.lastModified())return;Uri created=null;try{Uri uri=Uri.parse(tree),root=DocumentsContract.buildDocumentUriUsingTree(uri,DocumentsContract.getTreeDocumentId(uri)),children=DocumentsContract.buildChildDocumentsUriUsingTree(uri,DocumentsContract.getTreeDocumentId(uri));String name="PassPilot-Auto-Backup-"+new SimpleDateFormat("yyyyMMddHHmmssSSS",Locale.ROOT).format(new Date())+".json";created=DocumentsContract.createDocument(c.getContentResolver(),root,"application/json",name);if(created==null)throw new IOException();AppTools.copy(latest,c.getContentResolver().openOutputStream(created,"wt"));prefs.edit().putLong("lastSnapshot",latest.lastModified()).putString("lastAutoBackup",new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss",Locale.ROOT).format(new Date())).putString("backupError","").apply();List<String[]> versions=new ArrayList<>();try(Cursor cursor=c.getContentResolver().query(children,new String[]{DocumentsContract.Document.COLUMN_DOCUMENT_ID,DocumentsContract.Document.COLUMN_DISPLAY_NAME},null,null,null)){while(cursor!=null&&cursor.moveToNext())if(cursor.getString(1).matches("PassPilot-Auto-Backup-[0-9]{17}\\.json"))versions.add(new String[]{cursor.getString(0),cursor.getString(1)});}versions.sort((a,b)->b[1].compareTo(a[1]));for(int i=3;i<versions.size();i++)try{DocumentsContract.deleteDocument(c.getContentResolver(),DocumentsContract.buildDocumentUriUsingTree(uri,versions.get(i)[0]));}catch(Exception ignored){} }catch(Exception e){if(created!=null)try{DocumentsContract.deleteDocument(c.getContentResolver(),created);}catch(Exception ignored){}prefs.edit().putString("backupError","Backup-Ordner nicht erreichbar oder voll. Ordner prüfen / erneut wählen.").apply();}}
}
