package com.passpilot.app;
import org.jsoup.Jsoup;
import org.jsoup.nodes.*;
import org.json.*;
import java.net.*;
import java.util.*;
final class ManualFinder {
 static final Map<String,String[]> DOMAINS=new HashMap<>();
 static {DOMAINS.put("rowenta",new String[]{"rowenta.de","rowenta.com"});DOMAINS.put("tefal",new String[]{"tefal.de","tefal.com"});DOMAINS.put("bosch",new String[]{"bosch-professional.com","bosch-home.com","bosch-diy.com"});DOMAINS.put("siemens",new String[]{"siemens-home.bsh-group.com","siemens.com"});DOMAINS.put("sony",new String[]{"sony.de","sony.com","sony.eu","sony.net"});DOMAINS.put("samsung",new String[]{"samsung.com"});DOMAINS.put("razer",new String[]{"razer.com","razerzone.com"});DOMAINS.put("casio",new String[]{"casio.com"});DOMAINS.put("makita",new String[]{"makita.de","makita.com"});DOMAINS.put("miele",new String[]{"miele.de","miele.com"});DOMAINS.put("apple",new String[]{"apple.com"});DOMAINS.put("philips",new String[]{"philips.de","philips.com"});DOMAINS.put("canon",new String[]{"canon.de","canon.com","canon-europe.com"});DOMAINS.put("nikon",new String[]{"nikon.de","nikonimglib.com","nikon.com"});DOMAINS.put("panasonic",new String[]{"panasonic.com"});DOMAINS.put("lg",new String[]{"lg.com"});DOMAINS.put("logitech",new String[]{"logitech.com"});DOMAINS.put("yamaha",new String[]{"yamaha.com"});DOMAINS.put("bose",new String[]{"bose.com","bose.de"});DOMAINS.put("lenovo",new String[]{"lenovo.com"});DOMAINS.put("dell",new String[]{"dell.com"});DOMAINS.put("hp",new String[]{"hp.com"});DOMAINS.put("dyson",new String[]{"dyson.de","dyson.com"});}
 static boolean official(String brand,String url){try{String host=new URI(url).getHost();if(host==null)return false;for(String domain:DOMAINS.getOrDefault(brand.toLowerCase(Locale.ROOT),new String[0]))if(host.equals(domain)||host.endsWith("."+domain))return true;}catch(Exception ignored){}return false;}
 static String normalized(String s){return s.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]","");}
 static boolean modelMatch(String model,String content){String value=normalized(model);if(value.length()<4)return false;StringBuilder pattern=new StringBuilder("(?i)(?<![a-z0-9])");for(int i=0;i<value.length();i++){if(i>0)pattern.append("[\\s_/-]*");pattern.append(value.charAt(i));}pattern.append("(?![a-z0-9])");return java.util.regex.Pattern.compile(pattern.toString()).matcher(content).find();}
 static JSONObject candidate(String brand,String model,String title,String url,String context){try{if(!official(brand,url)||!url.startsWith("https://"))return null;boolean exact=modelMatch(model,title+" "+url+" "+context);if(!exact)return null;return AppTools.json("title",title.substring(0,Math.min(title.length(),180)),"url",url,"source","Herstellerquelle","confidence","Modell im Treffer enthalten – Inhalt prüfen","type",url.toLowerCase(Locale.ROOT).matches(".*\\.pdf(?:[?#].*)?")?"PDF":"Herstellerseite");}catch(Exception e){return null;}}
 static JSONArray search(String brand,String model){JSONArray results=new JSONArray();if(brand==null||model==null||brand.length()>80||model.length()>100||model.trim().length()<4)return results;String[] domains=DOMAINS.get(brand.toLowerCase(Locale.ROOT));if(domains==null)return results;Set<String> urls=new HashSet<>();if(brand.equalsIgnoreCase("Sony")&&normalized(model).equals("wh1000xm5")){String verified="https://helpguide.sony.net/mdr/wh1000xm5/v1/de/print.pdf";try{java.net.HttpURLConnection check=AppTools.connection(verified,"HEAD");if(check.getResponseCode()==200&&String.valueOf(check.getContentType()).contains("pdf")){JSONObject item=candidate(brand,model,"Sony WH-1000XM5 – Hilfe (Deutsch)",verified,"WH-1000XM5");if(item!=null){item.put("confidence","Modellzuordnung hinterlegt, PDF erreichbar – Inhalt prüfen");results.put(item);urls.add(verified);}}check.disconnect();}catch(Exception ignored){}}long deadline=System.currentTimeMillis()+22000;try{String query='"'+brand+'"'+" "+'"'+model+'"'+" Bedienungsanleitung manual PDF "+"("+String.join(" OR ",Arrays.stream(domains).map(d->"site:"+d).toArray(String[]::new))+")";Document search=Jsoup.connect("https://www.bing.com/search?format=rss&q="+URLEncoder.encode(query,"UTF-8")).parser(org.jsoup.parser.Parser.xmlParser()).timeout(9000).maxBodySize(500000).get();for(Element item:search.select("item")){String url=item.select("link").text(),title=item.select("title").text(),snippet=item.select("description").text();JSONObject c=candidate(brand,model,title,url,snippet);if(c==null||!urls.add(url))continue;results.put(c);if(results.length()>=6)break;}
 int original=results.length();for(int i=0;i<original&&i<3&&System.currentTimeMillis()<deadline;i++){JSONObject item=results.getJSONObject(i);String url=item.getString("url");if(url.toLowerCase(Locale.ROOT).contains(".pdf"))continue;try{Document page=Jsoup.connect(url).timeout(4500).maxBodySize(1000000).get();for(Element a:page.select("a[href]")){String link=a.absUrl("href");if(!link.toLowerCase(Locale.ROOT).contains(".pdf"))continue;JSONObject c=candidate(brand,model,a.text().isEmpty()?"PDF – "+model:a.text(),link,a.parent().text());if(c!=null&&urls.add(link)){results.put(c);if(results.length()>=8)return results;}}}catch(Exception ignored){}}}catch(Exception ignored){}return results;}
}
