'use strict';
// No public endpoint, payment provider or charge is enabled by this preparation.
const crypto=require('node:crypto');
const policy=require('./billing-policy.cjs');
function bindingId(provider,purchaseId){if(!['stripe','google-play','app-store'].includes(provider)||typeof purchaseId!=='string'||!purchaseId||purchaseId.length>500)throw Error('Ungültiger Zahlungsnachweis.');return crypto.createHash('sha256').update(provider+':'+purchaseId).digest('hex');}
async function cancelForUser({db,uid,cancelRenewal}){if(!uid||typeof cancelRenewal!=='function')throw Error('Verifizierter Kündigungsdienst fehlt.');const ref=db.doc('entitlements/'+uid),initial=await ref.get();if(!initial.exists)throw Error('Kein aktives Abo.');const before=initial.data();if(before.status==='cancelled')return before;policy.cancel(before,Date.now());const confirmed=await cancelRenewal(before.purchaseBinding);if(!confirmed||confirmed.cancelled!==true||confirmed.purchaseBinding!==before.purchaseBinding)throw Error('Kündigung beim Zahlungsanbieter noch nicht bestätigt.');return db.runTransaction(async tx=>{const snapshot=await tx.get(ref);if(!snapshot.exists||snapshot.data().purchaseBinding!==before.purchaseBinding)throw Error('Abo hat sich geändert. Bitte neu prüfen.');const current=snapshot.data();if(current.status==='cancelled')return current;const after=policy.cancel(current,Date.now());const stored={...after,accessUntil:new Date(policy.instant(after.accessUntil)),cancelledAt:new Date(policy.instant(after.cancelledAt))};tx.set(ref,stored);return stored;});}
// verifyPurchase must call the payment provider using server credentials; never trust client tier/expiry.
async function linkPurchase({db,uid,proof,verifyPurchase}){if(!uid||typeof verifyPurchase!=='function')throw Error('Verifizierter Zahlungsdienst fehlt.');const p=await verifyPurchase(proof);if(!p||!['plus','pro','family'].includes(p.tier)||!['active','revoked','past_due'].includes(p.status)||!policy.instant(p.paidThrough))throw Error('Zahlungsnachweis ungültig.');const id=bindingId(p.provider,p.purchaseId);return db.runTransaction(async tx=>{const binding=db.doc('purchaseBindings/'+id),entitlement=db.doc('entitlements/'+uid);const [bound,current]=await Promise.all([tx.get(binding),tx.get(entitlement)]);if(bound.exists&&bound.data().ownerUid!==uid)throw Error('Dieser Kauf ist bereits einem anderen Konto zugeordnet.');const old=current.exists?current.data():null;if(old?.purchaseBinding&&old.purchaseBinding!==id&&policy.access(old).tier!=='free')throw Error('Zuerst bestehenden Kauf klären.');const cancelled=old?.purchaseBinding===id&&old.status==='cancelled'&&p.status==='active'&&p.autoRenew!==true;const data={ownerUid:uid,tier:p.tier,status:cancelled?'cancelled':p.status,paidThrough:new Date(policy.instant(p.paidThrough)),accessUntil:new Date(cancelled?Math.max(policy.instant(old.accessUntil),policy.instant(p.paidThrough)):policy.instant(p.paidThrough)),purchaseBinding:id,autoRenew:cancelled?false:p.autoRenew===true,...(cancelled?{cancelledAt:old.cancelledAt}:{}),updatedAt:new Date()};tx.set(binding,{ownerUid:uid,provider:p.provider});tx.set(entitlement,data);return data;});}
module.exports={bindingId,cancelForUser,linkPurchase};
