(function(root){'use strict';
const DAY=86400000;
const tiers={free:{price:0,title:'Kostenlos',features:[]},plus:{price:3,title:'Plus',features:['syncUpload','dynamicPass','inventoryPdf','maintenanceAssistant','financeCharts','contractReminders']},pro:{price:7,title:'Pro',features:['syncUpload','dynamicPass','inventoryPdf','maintenanceAssistant','financeCharts','contractReminders','documentAI','assistantAI']}};
function instant(value){const t=typeof value==='number'?value:value instanceof Date?value.getTime():typeof value?.toMillis==='function'?value.toMillis():Date.parse(value);return Number.isFinite(t)&&t>0?t:0;}
function access(entitlement,now=Date.now()){if(!entitlement||!['active','cancelled','trialing','grace_period'].includes(entitlement.status)||!['plus','pro','family'].includes(entitlement.tier))return{tier:'free',until:0,features:[]};const until=instant(entitlement.accessUntil);if(!until||now>=until)return{tier:'free',until,features:[]};return{tier:entitlement.tier,until,features:[...tiers[entitlement.tier==='family'?'pro':entitlement.tier].features]};}
function permits(entitlement,feature,now){return access(entitlement,now).features.includes(feature);}
// Called only by the authenticated billing server after provider confirmation.
// Cancellation keeps existing confirmed access, never grants a new period.
function cancel(entitlement,now=Date.now()){if(!entitlement||!instant(now))throw Error('Ungültiger Kündigungszeitpunkt.');if(entitlement.status==='cancelled')return{...entitlement};if(entitlement.status!=='active'||access(entitlement,now).tier==='free')throw Error('Kein aktives Abo.');return{...entitlement,status:'cancelled',cancelledAt:new Date(now).toISOString(),accessUntil:new Date(Math.max(instant(entitlement.accessUntil),instant(entitlement.paidThrough))).toISOString(),autoRenew:false};}
const offers={free:{price:0,title:'Free',description:'Produkte, Fotos und Dokumente manuell verwalten. Eigene Daten bearbeiten, exportieren und löschen.'},plus:{price:3.99,title:'Plus',description:'Automatische Belegerkennung, Fristenüberwachung, Wartung, Finanzierungsdiagramme, Vertragsfristen, Smart-QR und Verkaufsdossiers. Neue Dienste werden schrittweise aktiviert.'},family:{price:5.99,title:'Family',description:'Alle Plus-Dienste für einen gemeinsamen Haushalt mit bis zu fünf Mitgliedern. Gemeinsamer Haushalt noch in Vorbereitung.'}};
const policy={DAY,tiers,offers,instant,access,permits,cancel};if(typeof module!=='undefined'&&module.exports)module.exports=policy;else root.PassPilotBillingPolicy=policy;
})(typeof window!=='undefined'?window:globalThis);
