'use strict';
const PROMPT=`Du bist die deutschsprachige PassPilot-Hilfe für Version 1.14. Antworte kurz, freundlich und konkret. Keine erfundenen Funktionen. Du hast keinen Zugriff auf Produkte, Konten, Rechnungen oder Bilddateien und führst keine Aktionen aus. Frage bei Unklarheit nach.
Produkt anlegen: + → Code live scannen oder Galerie → Rechnung → Produktfoto → Prüfen/Speichern; alle Bildschritte überspringbar. Unterlage und Lebenslauf beim Produkt hinzufügen, Verkaufen direkt wählen. Unter Mehr: Bearbeiten, QR-Pass, Übergeben, weitere Aktionen. Einstellungen: App & Website verbinden, Updates/Download, Hilfe, Backup. Weitere Einstellungen aufklappen für Gerätesperre, Erinnerungen und Speicher. Lokale Daten in localStorage/IndexedDB sind nicht zusätzlich verschlüsselt. Freiwillige Synchronisation mit bestätigtem Firebase-Konto und eigenem Sync-Passwort, AES-256-GCM, max20MB; Fotos/Dokumente nur nach zusätzlicher Auswahl. Keine dauerhafte Hintergrund-Synchronisation. Verlust ändert Status; Diebstahl bleibt privat im Lebenslauf auch nach dem Wiederfinden. Anleitungen nicht für jedes Modell auffindbar; Hersteller/Modell prüfen. Offline-QR bleibt Schnappschuss, Online-Pass kann deaktiviert werden. KI darf keine Garantie-, Eigentums- oder Rechtsansprüche bestätigen. Android-Kamera, PIN/NFC/Erinnerungen unterscheiden sich vom Browser. Keine KI-Funktionen zur automatischen Bestandsbearbeitung. Schlage bei Bedarf die lokale Hilfe oder passende Bedienelemente vor.`;
function createHandler({verifyToken,quota,providerKey,fetchImpl=fetch}){return async(req,res)=>{
 res.set('Cache-Control','no-store');res.set('X-Content-Type-Options','nosniff');
 const origin=req.headers.origin;const allowed=['https://passpilot-app.web.app','https://passpilot-69f7c.web.app'];if(origin&&!allowed.includes(origin))return res.status(403).json({error:'Diese Website ist nicht freigeschaltet.'});if(origin){res.set('Access-Control-Allow-Origin',origin);res.set('Vary','Origin');res.set('Access-Control-Allow-Headers','Content-Type, Authorization');res.set('Access-Control-Allow-Methods','POST, OPTIONS');}if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST')return res.status(405).json({error:'Nur POST erlaubt.'});
 try{const auth=req.headers.authorization||'';if(!auth.startsWith('Bearer '))return res.status(401).json({error:'Bitte zuerst anmelden.'});let user;try{user=await verifyToken(auth.slice(7));}catch{return res.status(401).json({error:'Bitte erneut anmelden.'});}if(user.email_verified!==true)return res.status(403).json({error:'Bitte zuerst deine E-Mail bestätigen und erneut anmelden.'});const body=req.body;if(!body||typeof body!=='object'||Array.isArray(body)||Object.keys(body).some(k=>k!=='question')||typeof body.question!=='string'||!body.question.trim()||body.question.length>800)return res.status(400).json({error:'Frage prüfen (höchstens 800 Zeichen).'});const key=providerKey();if(!key)return res.status(503).json({error:'Online-KI noch nicht freigeschaltet.'});if(!await quota(user.uid))return res.status(429).json({error:'KI-Limit erreicht. Bitte später erneut versuchen oder die lokale Hilfe nutzen.'});
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),18000);let response;try{response=await fetchImpl('https://api.openai.com/v1/responses',{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},body:JSON.stringify({model:'gpt-4.1-mini',store:false,instructions:PROMPT,input:body.question.trim(),max_output_tokens:500})});}finally{clearTimeout(timer);}if(!response.ok)return res.status(502).json({error:'KI-Dienst derzeit nicht verfügbar.'});const data=await response.json(),answer=(data.output||[]).flatMap(o=>o.content||[]).filter(c=>c.type==='output_text').map(c=>c.text).join('\n').trim();if(!answer||answer.length>6000)return res.status(502).json({error:'Keine gültige KI-Antwort erhalten.'});return res.status(200).json({answer});
 }catch{return res.status(503).json({error:'Online-KI vorübergehend nicht erreichbar. Lokale Hilfe bleibt verfügbar.'});}
};}
module.exports={createHandler,PROMPT};
