(function(global){
'use strict';
const base=new URL('./vendor/',location.href),asset=path=>new URL(path,base).href;
let workerPromise=null,queue=Promise.resolve(),progressCallback=null,pdfModule=null;
function loadScript(path){return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=asset(path);script.onload=resolve;script.onerror=()=>reject(Error('Erkennungsdateien nicht verfügbar. Beim ersten Start ist Internet erforderlich.'));document.head.append(script);});}
async function worker(){if(!workerPromise)workerPromise=(async()=>{if(!global.Tesseract)await loadScript('ocr/tesseract.min.js');return global.Tesseract.createWorker('deu+eng',1,{workerPath:asset('ocr/worker.min.js'),corePath:asset('ocr/core/'),langPath:asset('ocr/lang/'),workerBlobURL:false,logger:message=>{if(progressCallback)progressCallback(message.status==='recognizing text'?'Text wird gelesen: '+Math.round(message.progress*100)+' %':'Texterkennung wird vorbereitet …');}});})().catch(error=>{workerPromise=null;throw error;});return workerPromise;}
async function pdf(){if(!pdfModule)pdfModule=import(asset('pdf/pdf.mjs')).then(module=>{module.GlobalWorkerOptions.workerSrc=asset('pdf/pdf.worker.mjs');return module;});return pdfModule;}
async function imageText(file,engine,progress,retry=true,label=false){let best={text:'',confidence:0};const focus=label?await PassPilotRecognition.labelFocus(file):null;const passes=label?[{angle:0},...(focus?[{...focus,psm:6}]:[]),{angle:0,crop:{x:.06,y:.15,w:.88,h:.7},upscale:true,enhance:true,psm:6},{angle:90},{angle:270},{angle:180},{angle:20,enhance:true},{angle:340,enhance:true}]:[{angle:0},{angle:90},{angle:270},{angle:180}];for(const pass of passes){await engine.setParameters({tessedit_pageseg_mode:pass.psm|| (label?'11':'3')});const angle=pass.angle,canvas=await PassPilotRecognition.canvas(file,{...pass,enhance:pass.enhance||angle!==0});progress(angle?'Bildausrichtung wird geprüft …':'Text wird lokal gelesen …');const result=(await engine.recognize(canvas)).data;if(PassPilotRecognition.score(result.text)+result.confidence/10>PassPilotRecognition.score(best.text)+best.confidence/10)best=result;if(!retry||PassPilotRecognition.score(best.text)>=(label?45:30)&&best.confidence>=45)break;}return best.text.slice(0,50000);}
function readText(file,progress=()=>{},options={}){const run=async()=>{progressCallback=progress;let pdfDocument=null;try{file=await PassPilotRecognition.typed(file);progress('Texterkennung wird vorbereitet …');let engine=null;if(file.type==='application/pdf'){const module=await pdf();pdfDocument=await module.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false}).promise;if(pdfDocument.numPages>10)progress('Die ersten zehn PDF-Seiten werden gelesen.');let text='';for(let i=1;i<=Math.min(10,pdfDocument.numPages);i++){progress('PDF-Seite '+i+' / '+Math.min(10,pdfDocument.numPages)+' wird gelesen …');const page=await pdfDocument.getPage(i),content=await page.getTextContent();const extracted=content.items.map(item=>item.str+(item.hasEOL?'\n':' ')).join('');if(extracted.replace(/\s/g,'').length>=40){text+=extracted+'\n';continue;}const view=page.getViewport({scale:1}),scale=Math.min(2200/view.width,3000/view.height),viewport=page.getViewport({scale}),canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;engine ||= await worker();const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));text+=await imageText(blob,engine,progress)+ '\n';if(text.length>50000)break;}return text.slice(0,50000);}engine ||= await worker();await engine.setParameters({tessedit_pageseg_mode:options.label?'11':'3',preserve_interword_spaces:'1'});return imageText(file,engine,progress,options.retry!==false,options.label===true);}finally{if(pdfDocument)await pdfDocument.destroy();progressCallback=null;}};const result=queue.then(run,run);queue=result.catch(()=>{});return result;}

function code(result){const formats=['aztec','codabar','code_39','code_93','code_128','data_matrix','ean_8','ean_13','itf','','pdf417','qr_code','','','upc_a','upc_e'];return{rawValue:result.getText(),format:formats[result.getBarcodeFormat()]||''};}
async function readCodeImage(file,progress){let barcodes=[];const bitmap=await createImageBitmap(file);try{if(global.BarcodeDetector){const formats=await BarcodeDetector.getSupportedFormats();const detector=new BarcodeDetector({formats});barcodes=(await detector.detect(bitmap)).map(r=>({rawValue:r.rawValue,format:r.format}));}else if(global.ZXingBrowser){const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d').drawImage(bitmap,0,0);try{barcodes=[code(new global.ZXingBrowser.BrowserMultiFormatReader().decodeFromCanvas(canvas))];}catch{}}}finally{bitmap.close();}let text='';try{text=await readText(file,progress,{label:true,retry:!barcodes.some(b=>PassPilotScan.validGtin(b.rawValue.replace(/\s/g,'')))});}catch(error){if(!barcodes.length)throw error;}return{text,barcodes};}
async function startLive(video,stream,callback){const reader=new global.ZXingBrowser.BrowserMultiFormatReader();return reader.decodeFromStream(stream,video,(result)=>{if(result)callback([code(result)]);});}
async function createPdf(encoded){if(!global.PDFLib)await loadScript('pdf-lib.min.js');const images=JSON.parse(encoded);if(!Array.isArray(images)||!images.length||images.length>20)throw Error('Bitte 1 bis 20 Bildseiten wählen.');const document=await PDFLib.PDFDocument.create();for(const image of images){const bytes=new Uint8Array(await (await fetch(image)).arrayBuffer()),embedded=String(image).startsWith('data:image/png')?await document.embedPng(bytes):await document.embedJpg(bytes);const page=document.addPage([595.28,841.89]),scale=Math.min(555/embedded.width,801/embedded.height);page.drawImage(embedded,{x:(595.28-embedded.width*scale)/2,y:(841.89-embedded.height*scale)/2,width:embedded.width*scale,height:embedded.height*scale});}const bytes=await document.save();if(bytes.length>20*1024*1024)throw Error('PDF zu groß. Bitte weniger Seiten wählen.');let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return{ok:true,data:btoa(binary)};}
async function openPdf(blob,name){
 const url=URL.createObjectURL(new Blob([blob],{type:'application/pdf'}));
 modal(`<div class="modal-head"><h2>${esc(name)}</h2><button class="icon-btn" data-action="close-modal">✕</button></div><div id="webPdfView"><div class="detail-actions"><button type="button" class="ghost-btn" data-pdf-action="previous">‹ Seite</button><span id="webPdfCounter" role="status">PDF wird geöffnet …</span><button type="button" class="ghost-btn" data-pdf-action="next">Seite ›</button><button type="button" class="ghost-btn" data-pdf-action="smaller">−</button><button type="button" class="ghost-btn" data-pdf-action="larger">+</button><a class="ghost-btn" href="${url}" download="${esc(name)}">Herunterladen</a></div><div class="web-pdf-scroll"><canvas id="webPdfCanvas" aria-label="PDF-Seite"></canvas></div><details><summary>Text dieser Seite</summary><pre id="webPdfText"></pre></details></div>`);
 const container=globalThis.document.getElementById('webPdfView'),counter=container.querySelector('#webPdfCounter');let closed=false,pdfDocument=null,page=1,zoom=1,rendering=false;
 const close=()=>{closed=true;URL.revokeObjectURL(url);if(pdfDocument)pdfDocument.destroy();};globalThis.document.getElementById('modal').addEventListener('close',close,{once:true});
 const show=async()=>{if(closed||rendering||!pdfDocument)return;rendering=true;const buttons=[...container.querySelectorAll('[data-pdf-action]')];buttons.forEach(button=>button.disabled=true);try{const current=await pdfDocument.getPage(page),view=current.getViewport({scale:1}),width=Math.max(250,container.clientWidth),scale=Math.min(2, width/view.width)*zoom,viewport=current.getViewport({scale}),canvas=container.querySelector('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await current.render({canvasContext:canvas.getContext('2d'),viewport}).promise;if(closed)return;counter.textContent=`${page} / ${pdfDocument.numPages} · ${Math.round(zoom*100)} %`;const text=await current.getTextContent();if(!closed)container.querySelector('#webPdfText').textContent=text.items.map(item=>item.str+(item.hasEOL?'\n':' ')).join('');}finally{rendering=false;buttons.forEach(button=>button.disabled=false);}};
 container.addEventListener('click',event=>{const action=event.target.closest('[data-pdf-action]')?.dataset.pdfAction;if(!action||rendering||!pdfDocument)return;if(action==='previous')page=Math.max(1,page-1);if(action==='next')page=Math.min(pdfDocument.numPages,page+1);if(action==='smaller')zoom=Math.max(.5,zoom-.25);if(action==='larger')zoom=Math.min(3,zoom+.25);show().catch(error=>{counter.textContent='Seite konnte nicht angezeigt werden. PDF herunterladen ist weiterhin möglich.';});});
 try{const module=await pdf();pdfDocument=await module.getDocument({data:new Uint8Array(await blob.arrayBuffer()),isEvalSupported:false}).promise;if(closed||!globalThis.document.contains(container)){pdfDocument.destroy();return;}await show();}catch(error){if(!closed)counter.textContent='PDF konnte nicht angezeigt werden (geschützt oder beschädigt). Herunterladen ist weiterhin möglich.';}
}
const knownManuals=[{brand:'Sony',model:'WH-1000XM5',title:'Sony WH-1000XM5 – Hilfe (Deutsch)',url:'https://helpguide.sony.net/mdr/wh1000xm5/v1/de/print.pdf',source:'Herstellerquelle',type:'PDF',confidence:'Hinterlegte Modellzuordnung – Inhalt prüfen'}];
async function call(method,...args){if(method==='readReceipt'){const blob=await(await fetch(args[0])).blob();return{ok:true,text:await readText(blob)};}if(method==='createPdf')return createPdf(args[0]);if(method==='findManual'){const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');const results=knownManuals.filter(m=>norm(m.brand)===norm(args[0])&&norm(m.model)===norm(args[1]));if(results.length)return{results,status:'found'};if(!global.PassPilotFirebase?.user())return{results:[],status:'unsupported'};const cfg=PassPilotFirebase.config(),response=await fetch('https://europe-west3-'+cfg.projectId+'.cloudfunctions.net/passpilotFindManual',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+await PassPilotFirebase.token()},body:JSON.stringify({brand:args[0],model:args[1]}),signal:AbortSignal.timeout(25000)});if(!response.ok)throw Error(response.status===404?'Automatischer Web-Suchdienst ist noch nicht veröffentlicht.':'Hersteller-Suchdienst nicht erreichbar.');return response.json();}if(method==='checkLink'){const url=PassPilotManuals.safeUrl(args[0]);if(!url)return{status:'unknown'};try{const response=await fetch(url,{method:'HEAD',credentials:'omit',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(8000)});return{status:response.ok?'ok':[404,410].includes(response.status)?'gone':'unknown'};}catch{return{status:'unknown'};}}if(method==='downloadPdf'){const url=PassPilotManuals.safeUrl(args[0]);if(!url)throw Error('Ungültiger PDF-Link.');let response;try{response=await fetch(url,{credentials:'omit',referrerPolicy:'no-referrer'});}catch{throw Error('Der Hersteller erlaubt keinen direkten Browser-Download. Link öffnen, PDF herunterladen und über „PDF lokal speichern“ auswählen.');}if(!response.ok)throw Error('PDF nicht erreichbar.');const blob=await response.blob();if(blob.size>20*1024*1024)throw Error('PDF ist größer als 20 MB.');if(!(await blob.slice(0,5).text()).startsWith('%PDF-'))throw Error('Der Link liefert keine PDF. Bitte Herstellerseite öffnen.');const data=await blobToDataUrl(new Blob([blob],{type:'application/pdf'}));return{data:data.split(',')[1]};}throw Error('Diese Funktion steht im Browser nicht zur Verfügung.');}
global.PassPilotWebTools={supports:method=>['readReceipt','createPdf','findManual','downloadPdf','checkLink'].includes(method),call,readText,readCodeImage,startLive,openPdf,barcodeAvailable:!!global.ZXingBrowser};
})(window);
